package seed

import (
	"log"
	"rpg-manager/internal/domain"

	"gorm.io/gorm"
)

// Poderes adicionais extraídos do sourcebook "Poder Marcial" (Martial Power) para
// as classes marciais: Guerreiro, Ladino e Patrulheiro. O capítulo do Comandante
// de Guerra (Warlord) foi ignorado pois essa classe ainda não existe no banco.
// Este arquivo é independente de seed.go e não é chamado automaticamente
// pelo seed.Run — a conexão deve ser feita manualmente.

func seedGuerreiroSkillsPoderMarcial(db *gorm.DB) {
	var cls domain.Class
	if err := db.Where("name = ? AND edition = ?", "Guerreiro", "4e").First(&cls).Error; err != nil {
		log.Println("  ✗ Guerreiro 4e não encontrado")
		return
	}
	id := cls.ID

	skills := []domain.Skill{
		// ── CARACTERÍSTICAS DE CLASSE ALTERNATIVAS (em vez de Aptidão com Armas) ──
		{
			Name: "Técnica Tempestuosa", Edition: "4e", ClassID: &id,
			Description: "Você dispensa o escudo em favor de uma segunda arma, confiando na velocidade para compensar a falta de proteção.",
			Effect:      "Enquanto empunhando duas armas corpo a corpo, o guerreiro recebe +1 de bônus nas jogadas de ataque com armas que tenham a propriedade mão inábil. Ele também adquire o talento Defesa com Duas Armas mesmo sem cumprir os pré-requisitos. Enquanto usando armadura leve ou cota de malha, o guerreiro também recebe +1 de bônus de dano (+2 se empunhando maça, machado, martelo ou picareta) nas jogadas de dano corpo a corpo e contíguas realizadas com uma arma, sempre que estiver empunhando duas armas.",
			Special:        "Alternativa à Aptidão com Armas do Guerreiro; recomendada para a estrutura de guerreiro tempestuoso.",
			PowerType: domain.PowerUtility, Level: 1, IsClassFeature: true, RequiresChoice: true,
		},
		{
			Name: "Vigor Impetuoso", Edition: "4e", ClassID: &id,
			Description: "Seu ímpeto na batalha o fortalece a cada golpe desferido.",
			Effect:      "Sempre que atingir um inimigo com um ataque corpo a corpo ou contíguo, o guerreiro recebe pontos de vida temporários iguais ao seu modificador de Constituição, somados aos já concedidos pelo poder. Além disso, quando usa um poder de guerreiro com a palavra-chave revigorante e não atinge nenhum alvo, recebe pontos de vida temporários iguais ao seu valor de Constituição.",
			Special:        "Alternativa à Aptidão com Armas do Guerreiro; recomendada para a estrutura de guerreiro impetuoso.",
			PowerType: domain.PowerUtility, Level: 1, IsClassFeature: true, RequiresChoice: true,
		},

		// ── SEM LIMITE DE NÍVEL 1 ──────────────────────────────────
		{
			Name: "Golpe Precipitado", Edition: "4e", ClassID: &id,
			Description: "Com um grito de batalha, você joga o peso do seu corpo no ataque.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força + 2 vs. CA",
			Hit:          "1[A] + mod Força de dano.",
			Special:      "Arma: Maça, machado ou martelo causam dano adicional igual ao mod Constituição.",
			Effect:       "O guerreiro concede vantagem de combate ao alvo até o começo do seu próximo turno.",
			LevelScaling: "Nível 21: 2[A] + mod Força de dano.",
			PowerType: domain.PowerUnlimited, Level: 1,
		},
		{
			Name: "Ímpeto Esmagador", Edition: "4e", ClassID: &id,
			Description: "A sensação de sua arma contra o inimigo traz seu coração de volta à luta.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:          "1[A] + mod Força de dano.",
			LevelScaling: "Nível 21: 2[A] + mod Força de dano.",
			PowerType: domain.PowerUnlimited, Level: 1,
		},

		// ── POR ENCONTRO DE NÍVEL 1 ────────────────────────────────
		{
			Name: "Choque com Escudo", Edition: "4e", ClassID: &id,
			Description: "Você atinge o oponente com o escudo, tirando o equilíbrio dele, e segue com um golpe bem colocado.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Corpo a corpo 1",
			Special: "Condição: O guerreiro deve empunhar um escudo.",
			Target:  "Uma criatura", Attack: "Força + 2 vs. Reflexos",
			Hit:    "1d10 + mod Força de dano e o alvo é empurrado 1 quadrado e fica derrubado.",
			Effect: "Especial: Se o guerreiro for um anão, o ataque causa dano adicional igual ao mod Sabedoria. Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Enxurrada Distrativa", Edition: "4e", ClassID: &id,
			Description: "Sua rajada de fintas e golpes deixam as defesas do oponente abaladas.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano e o alvo concede vantagem de combate ao guerreiro até o final do próximo turno dele.",
			Special: "Arma: Se o guerreiro estiver empunhando duas armas corpo a corpo, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Estremecer", Edition: "4e", ClassID: &id,
			Description: "Você estoura sua arma contra o oponente, abalando seus órgãos vitais.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Fortitude",
			Hit:     "O alvo fica pasmo até o final do próximo turno do guerreiro.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Golpe com Impulso", Edition: "4e", ClassID: &id,
			Description: "Você salta contra um oponente que estava além do seu alcance.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo +1 de alcance",
			Target: "Uma criatura", Attack: "Força -1 vs. CA",
			Hit: "2[A] + mod Força de dano.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Golpe Criterioso", Edition: "4e", ClassID: &id,
			Description: "Seu oponente está demonstrando fraqueza e sua perspicácia lhe permite tirar proveito disso.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano.",
			Special: "Arma: Se o alvo estiver sangrando, o ataque causa dano adicional igual ao mod Sabedoria do guerreiro.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Rajada Condutiva", Edition: "4e", ClassID: &id,
			Description: "Com golpes semelhantes a bote de serpentes, você força dois inimigos a se moverem para onde você desejar.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Duas criaturas", Attack: "Força vs. CA (arma principal e arma da mão inábil), um ataque por alvo",
			Hit: "1[A] + mod Força de dano e o alvo é conduzido 1 quadrado.",
			PowerType: domain.PowerEncounter, Level: 1,
		},

		// ── DIÁRIAS DE NÍVEL 1 ─────────────────────────────────────
		{
			Name: "Ameaça Duradoura", Edition: "4e", ClassID: &id,
			Description: "Seguindo seu desafio com um ataque sólido, você força o inimigo a engajá-lo em combate.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit: "3[A] + mod Força de dano e o alvo fica marcado até o final do encontro ou até ficar inconsciente. Nenhuma outra marca pode substituir essa marca.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Assalto Pelos Flancos", Edition: "4e", ClassID: &id,
			Description: "A presença de tantos inimigos subjuga o seu oponente, dando a você a oportunidade de lançar um ataque violento.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura flanqueada pelo guerreiro", Attack: "Força vs. CA",
			Hit:  "3[A] + mod Força de dano. Para cada aliado do guerreiro adjacente ao alvo, o ataque causa dano adicional igual ao mod Destreza.",
			Miss: "Metade do dano.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Dança Tempestuosa", Edition: "4e", ClassID: &id,
			Description: "Você salta de um inimigo para o inimigo, dando a cada um deles o sabor amargo de sua arma.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "1[A] + mod Força de dano. Se o guerreiro tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			Effect: "O guerreiro ajusta 1 quadrado e repete o ataque contra um segundo alvo. Depois, ajusta mais 1 quadrado e repete o ataque contra um terceiro alvo.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Embuste de Acuar", Edition: "4e", ClassID: &id,
			Description: "Seus ataques violentos prometem ao seu oponente uma perseguição que só vai acabar quando um de vocês for vitorioso.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "3[A] + mod Força de dano.",
			Effect: "Até o final do encontro, sempre que o alvo se mover, o guerreiro pode usar uma reação imediata para ajustar um número de quadrados igual ao seu mod Destreza.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Quebrar os Joelhos", Edition: "4e", ClassID: &id,
			Description: "Ao golpear as pernas do oponente você faz com que a mera tentativa de movimento seja extremamente dolorosa para ele.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano e o alvo fica lento (TR encerra). Se já estiver lento, o alvo fica imobilizado (TR encerra).",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			Miss:    "Metade do dano e o alvo não fica lento nem imobilizado.",
			PowerType: domain.PowerDaily, Level: 1,
		},

		// ── UTILITÁRIAS DE NÍVEL 2 ─────────────────────────────────
		{
			Name: "Criar Abertura", Edition: "4e", ClassID: &id,
			Description: "Você atrai a atenção de seu inimigo, criando uma oportunidade para um aliado escapar.",
			Keywords: "Marcial", ActionType: "Ação Mínima", Range: "Corpo a corpo 1",
			Target: "Uma criatura",
			Effect: "O alvo fica marcado até o final do próximo turno do guerreiro. Ele pode então realizar um ataque básico corpo a corpo contra o personagem usando uma ação livre, com -2 de penalidade na jogada de ataque. Usando uma ação livre, um aliado do guerreiro que estiver adjacente ao alvo ajusta um número de quadrados igual ao seu próprio deslocamento.",
			PowerType: domain.PowerEncounter, Level: 2,
		},
		{
			Name: "Flancos Protegidos", Edition: "4e", ClassID: &id,
			Description: "Você rodopia com o escudo, concentrando-se em cobrir qualquer abertura em sua guarda.",
			Keywords: "Marcial", ActionType: "Ação Mínima", Range: "Pessoal",
			Special: "Condição: O guerreiro deve empunhar um escudo.",
			Effect:  "Até o final do próximo turno do guerreiro, ele recebe +2 de bônus de poder na CA e na defesa de Reflexos e não concede vantagem de combate às criaturas que estiverem flanqueando.",
			PowerType: domain.PowerEncounter, Level: 2,
		},
		{
			Name: "Passar Adiante", Edition: "4e", ClassID: &id,
			Description: "Com precisão, você ultrapassa seu oponente sem baixar a guarda.",
			Keywords: "Marcial", ActionType: "Ação de Movimento", Range: "Pessoal",
			Effect: "O personagem escolhe um inimigo adjacente e percorre seu deslocamento, contanto que termine o movimento num quadrado adjacente ao inimigo; este movimento não provoca ataques de oportunidade.",
			PowerType: domain.PowerUnlimited, Level: 2,
		},
		{
			Name: "Postura Defensiva", Edition: "4e", ClassID: &id,
			Description: "Recuando em uma postura cautelosa, você se movimenta ao redor dos ataques do oponente até obter uma posição vantajosa.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, o guerreiro fica lento e recebe +2 de bônus de poder na CA. Além disso, sempre que um inimigo fracassar num ataque básico contra o personagem, este pode ajustar 1 quadrado usando uma reação imediata. O guerreiro pode encerrar esta postura usando uma ação livre.",
			PowerType: domain.PowerDaily, Level: 2,
		},
		{
			Name: "Reposicionamento Perspicaz", Edition: "4e", ClassID: &id,
			Description: "O ataque do inimigo o acerta, mas ainda assim você encontra uma forma de aperfeiçoar sua posição.",
			Keywords: "Marcial", ActionType: "Reação Imediata", Range: "Pessoal",
			Special: "Gatilho: O guerreiro é atingido por um ataque.",
			Effect:  "O personagem ajusta um número de quadrados igual ao seu mod Sabedoria.",
			PowerType: domain.PowerEncounter, Level: 2,
		},

		// ── POR ENCONTRO DE NÍVEL 3 ────────────────────────────────
		{
			Name: "Avanço com Impulso", Edition: "4e", ClassID: &id,
			Description: "Você salta para frente e realiza um ataque veloz.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Effect:  "O guerreiro ajusta 1 quadrado antes do ataque. Arma: Se estiver empunhando uma lâmina leve ou lança, ajusta 2 quadrados antes do ataque e 1 quadrado depois do ataque.",
			Hit:     "2[A] + mod Força de dano. Se o guerreiro tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Bloquear e Responder", Edition: "4e", ClassID: &id,
			Description: "Você apara um ataque e rapidamente reage, tirando o equilíbrio do oponente.",
			Keywords: "Arma, Marcial", ActionType: "Reação Imediata", Range: "Arma corpo a corpo",
			Special: "Gatilho: Um inimigo fracassa num ataque corpo a corpo contra o guerreiro ou um aliado.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit: "1[A] + mod Força de dano e o alvo concede vantagem de combate ao guerreiro e seus aliados até o final do próximo turno do personagem.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Esquadrinhar", Edition: "4e", ClassID: &id,
			Description: "Com um golpe preciso, você encontra um ponto falho na guarda do inimigo.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Reflexos",
			Hit:     "1[A] + mod Força de dano e o guerreiro recebe +4 de bônus de poder na próxima jogada de ataque contra o alvo até o final do próximo turno.",
			Special: "Especial: Quando realizar um ataque de oportunidade, o personagem pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Golpe do Rinoceronte", Edition: "4e", ClassID: &id,
			Description: "Adentrando a batalha, você golpeia os oponentes com ataques impetuosos.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve realizar uma investida e usar este poder no lugar de um ataque básico corpo a corpo. Se estiver empunhando um escudo, o movimento realizado durante a investida não provoca ataques de oportunidade.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit: "2[A] + mod Força de dano.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Pancada Cegante", Edition: "4e", ClassID: &id,
			Description: "Um golpe brusco deixa o inimigo vendo estrelas.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Fortitude",
			Hit:     "O alvo fica cego até o final do próximo turno do guerreiro.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Pancada com Escudo", Edition: "4e", ClassID: &id,
			Description: "Depois de um ataque bem-sucedido, você golpeia o inimigo com o escudo, derrubando-o.",
			Keywords: "Marcial", ActionType: "Ação Livre", Range: "Corpo a corpo 1",
			Special: "Gatilho: O guerreiro atinge um inimigo com um ataque corpo a corpo. Condição: O guerreiro deve empunhar um escudo.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força + 2 vs. Fortitude",
			Hit: "O alvo é empurrado 1 quadrado e fica derrubado.",
			PowerType: domain.PowerEncounter, Level: 3,
		},

		// ── DIÁRIAS DE NÍVEL 5 ─────────────────────────────────────
		{
			Name: "Acossar da Retaguarda", Edition: "4e", ClassID: &id,
			Description: "Com uma estocada violenta você empurra o inimigo para trás, protegendo-se dele com sua arma de alcance.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de alcance.",
			Target:  "Uma criatura", Attack: "Força vs. Fortitude",
			Hit:    "2[A] + mod Força de dano e o alvo é empurrado 1 quadrado.",
			Effect: "Especial: Se o guerreiro for um eladrin, o ataque causa dano adicional igual ao mod Destreza. Até o final do encontro, sempre que o alvo ajustar ou realizar um ataque que não inclua o guerreiro como alvo, o personagem pode ajustar 1 quadrado e realizar um ataque básico corpo a corpo contra o alvo, usando uma interrupção imediata.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Assalto Agonizante", Edition: "4e", ClassID: &id,
			Description: "Seu ataque atinge o adversário em uma área sensível, fazendo com que ele se curve de dor.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano e o alvo fica pasmo e imobilizado (TR encerra ambos).",
			Special: "Arma: Se o guerreiro estiver empunhando um mangual, o ataque causa dano adicional igual ao mod Destreza.",
			Miss:    "Metade do dano e o alvo não fica pasmo nem imobilizado.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Assalto Molestador", Edition: "4e", ClassID: &id,
			Description: "Enquanto um aliado distrai seu oponente, você o ataca.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "2[A] + mod Força de dano.",
			Effect: "Até o final do encontro, uma vez por rodada, sempre que um aliado do guerreiro atingir o alvo com um ataque corpo a corpo, o personagem pode realizar um ataque básico corpo a corpo com vantagem de combate contra o alvo.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Corte Sutil", Edition: "4e", ClassID: &id,
			Description: "Você realiza uma manobra habilidosa, cortando o inimigo, tirando seu sangue e deixando-o lento de dor.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma lâmina leve.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Effect: "O guerreiro ajusta 1 quadrado antes e depois do ataque.",
			Hit:    "O alvo fica lento e sofre dano contínuo igual a 10 + mod Destreza do personagem (TR encerra ambos).",
			Miss:   "O alvo sofre dano contínuo igual ao mod Destreza do personagem (TR encerra).",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Investida do Cometa", Edition: "4e", ClassID: &id,
			Description: "Você salta na direção do inimigo, aterrissando com um som estrondoso.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Pré-requisito: O guerreiro deve ser treinado em Atletismo. Condição: O guerreiro deve realizar uma investida e usar este poder no lugar de um ataque básico corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit:  "3[A] + mod Força + mod Constituição de dano.",
			Miss: "Metade do dano.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Pancada Restritiva", Edition: "4e", ClassID: &id,
			Description: "Você golpeia seu oponente, fazendo-o cair de joelhos e nesse momento, o imobiliza.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Corpo a corpo 1",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "1[A] + mod Força de dano e o alvo fica imobilizado enquanto estiver adjacente ao guerreiro.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			Miss:    "Metade do dano e o alvo fica imobilizado até o final do próximo turno do personagem.",
			PowerType: domain.PowerDaily, Level: 5,
		},

		// ── UTILITÁRIAS DE NÍVEL 6 ─────────────────────────────────
		{
			Name: "Acerto de Contas", Edition: "4e", ClassID: &id,
			Description: "No momento em que você é atingido, sua determinação traça o destino de seu inimigo. Ele será derrubado.",
			Keywords: "Marcial", ActionType: "Reação Imediata", Range: "Pessoal",
			Special: "Gatilho: O guerreiro é atingido por um ataque.",
			Effect:  "Até o final do encontro, o personagem recebe +2 de bônus de poder nas jogadas de ataque contra o inimigo que ativou o gatilho.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		{
			Name: "Aproximação Ágil", Edition: "4e", ClassID: &id,
			Description: "Você realiza um rápido ajuste para uma posição mais vantajosa.",
			Keywords: "Marcial", ActionType: "Ação de Movimento", Range: "Pessoal",
			Effect: "O guerreiro ajusta 2 quadrados, contanto que termine o movimento adjacente a um inimigo. Se não estiver vestindo uma armadura pesada, o personagem ajusta 3 quadrados.",
			PowerType: domain.PowerEncounter, Level: 6,
		},
		{
			Name: "Estabilidade Rochosa", Edition: "4e", ClassID: &id,
			Description: "Você direciona seu centro de gravidade para baixo e cerra os dentes. Você não vai a lugar algum.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, o guerreiro não pode ser derrubado e sempre que for puxado, empurrado ou conduzido, pode reduzir o movimento forçado em 1 quadrado.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		{
			Name: "Foco Poderoso", Edition: "4e", ClassID: &id,
			Description: "A concentração aumenta sua habilidade de realizar façanhas de força.",
			Keywords: "Marcial", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Até o final do próximo turno do guerreiro, ele recebe um bônus nos testes de Atletismo e de Força igual ao seu mod Sabedoria.",
			PowerType: domain.PowerEncounter, Level: 6,
		},
		{
			Name: "Protetor Vigilante", Edition: "4e", ClassID: &id,
			Description: "Você rodopia o escudo para proteger seus aliados.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Special: "Condição: O guerreiro deve empunhar um escudo.",
			Effect:  "Enquanto adotar esta postura, o personagem sofre -5 de penalidade na CA, mas seus aliados adjacentes recebem +2 de bônus de poder na CA e na defesa de Reflexos. Especial: Se o guerreiro for um draconato, o bônus aumenta para +3.",
			PowerType: domain.PowerDaily, Level: 6,
		},

		// ── POR ENCONTRO DE NÍVEL 7 ────────────────────────────────
		{
			Name: "Bloqueio Selvagem", Edition: "4e", ClassID: &id,
			Description: "Com uma velocidade devastadora você violentamente apara o golpe, causando dor ao oponente como punição pelo ataque imprudente.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Interrupção Imediata", Range: "Arma corpo a corpo",
			Special: "Gatilho: Um inimigo atinge um aliado do guerreiro com um ataque corpo a corpo.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit:     "Mod Força de dano e o aliado sofre metade do dano causado pelo ataque que ativou o gatilho.",
			Special2: "",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Não Tão Rápido", Edition: "4e", ClassID: &id,
			Description: "Seu adversário tenta fugir, mas usando sua arma você o mantém exatamente onde ele está.",
			Keywords: "Arma, Marcial", ActionType: "Interrupção Imediata", Range: "Corpo a corpo 1",
			Special: "Gatilho: Um inimigo adjacente se afasta do guerreiro.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit:     "1[A] + mod Força de dano e o alvo fica lento até o final do próximo turno do guerreiro.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "No Chão!", Edition: "4e", ClassID: &id,
			Description: "Qual o problema de atacar alguém caído?",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit: "2[A] + mod Força de dano. Se o alvo estiver derrubado, o ataque causa dano adicional igual ao mod Destreza e o alvo não pode se levantar até o final do próximo turno do guerreiro.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Rajada Restritiva", Edition: "4e", ClassID: &id,
			Description: "Usando as duas armas, você ataca as pernas do oponente, deixando-o lento devido aos dolorosos ferimentos.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA (arma principal e arma da mão inábil), dois ataques",
			Hit: "1[A] + mod Força de dano por ataque e o alvo fica lento até o final do próximo turno do guerreiro. Se obtiver sucesso nos dois ataques, o segundo ataque causa dano adicional igual ao mod Destreza do personagem.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Tombar", Edition: "4e", ClassID: &id,
			Description: "Seus cortes cuidadosos deixam dois oponentes cambaleando em agonia.",
			Keywords: "Marcial", ActionType: "Ação Livre", Range: "Arma corpo a corpo",
			Special: "Gatilho: O personagem atinge um inimigo com um ataque básico corpo a corpo.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. Reflexos",
			Hit:     "1[A] + mod Força de dano e o alvo fica lento até o final do próximo turno do guerreiro.",
			Special2: "Arma: Se o guerreiro estiver empunhando uma arma de haste ou lança, o alvo fica derrubado em vez de lento.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Tormento Duplo", Edition: "4e", ClassID: &id,
			Description: "Seus ataques deixam dois oponentes cambaleando em agonia.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Duas criaturas", Attack: "Força vs. CA (arma principal e arma da mão inábil), um ataque por alvo",
			Hit: "1[A] + mod Força de dano e o alvo é empurrado um número de quadrados igual a 1 + mod Destreza do guerreiro. Se o personagem tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 7,
		},

		// ── DIÁRIAS DE NÍVEL 9 ─────────────────────────────────────
		{
			Name: "Ferimento Incômodo", Edition: "4e", ClassID: &id,
			Description: "Os ferimentos infligidos por seus ataques se abrem na medida em que o oponente tenta se mover.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "3[A] + mod Força de dano. Se o alvo se mover antes do final do seu próximo turno, ele sofre dano adicional igual ao mod Força do guerreiro.",
			Special: "Arma: Se o guerreiro estiver empunhando uma picareta, o dano adicional é igual ao mod Força + mod Constituição do personagem.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Golpe do Chacal", Edition: "4e", ClassID: &id,
			Description: "Sentindo a fraqueza do seu inimigo, você se move para abatê-lo.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Livre", Range: "Arma corpo a corpo",
			Special: "Gatilho: Um inimigo marcado pelo guerreiro fica sangrando.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit: "3[A] + mod Força de dano.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Impacto Aterrorizante", Edition: "4e", ClassID: &id,
			Description: "Soltando um exaltado grito de batalha, você pulveriza o oponente e impõe pavor aos inimigos próximos.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura (alvo primário)", Attack: "Força vs. CA (ataque primário)",
			Hit:     "2[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque primário causa dano adicional igual ao mod Constituição.",
			Effect:  "O guerreiro realiza um ataque secundário, que adquire a palavra-chave medo. Alvo Secundário: Os inimigos a até 3 quadrados do alvo primário. Ataque Secundário: Constituição vs. Vontade. Sucesso: O alvo é empurrado 1 quadrado.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Impedir Estocada", Edition: "4e", ClassID: &id,
			Description: "Com o inimigo se movimentando para atacar, você responde avançando rapidamente e golpeando.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Reação Imediata", Range: "Arma corpo a corpo",
			Special: "Gatilho: Um inimigo ingressa num quadrado a até 2 quadrados do guerreiro.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Effect:  "O guerreiro ajusta 2 quadrados antes do ataque.",
			Hit:     "1[A] + mod Força de dano e o alvo fica imobilizado até o começo do próximo turno do personagem.",
			Special2: "Especial: Se o alvo se deslocou como parte de uma investida, ele pode atacar o guerreiro no lugar do alvo original da investida.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Recuperação do Guerreiro", Edition: "4e", ClassID: &id,
			Description: "Ao golpear, você usa sua força vital para se acalmar e concentrar, recuperando o vigor para a luta que está por vir.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "3[A] + mod Força de dano.",
			Effect: "Se já tiver utilizado todos os seus poderes de ataque por encontro, o guerreiro recupera a utilização de um poder de ataque por encontro que tenha usado durante este encontro.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Zombaria", Edition: "4e", ClassID: &id,
			Description: "Com um ataque preciso e provocativo, você marca o inimigo e o desafia, sob pena de sofrer um novo ataque.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "3[A] + mod Força de dano. Se o guerreiro tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			Effect: "O alvo fica marcado (TR encerra). Se o alvo não atacar o guerreiro em seu turno enquanto marcado, o personagem pode realizar um ataque contra ele ou ajustar 1 quadrado para perto dele usando uma ação livre.",
			PowerType: domain.PowerDaily, Level: 9,
		},

		// ── UTILITÁRIAS DE NÍVEL 10 ────────────────────────────────
		{
			Name: "Buscar Força no Sofrimento", Edition: "4e", ClassID: &id,
			Description: "As dores de seus ferimentos abrem as comportas de sua força interior.",
			Keywords: "Marcial", ActionType: "Ação Mínima", Range: "Pessoal",
			Special: "Condição: O guerreiro deve estar sangrando.",
			Effect:  "O personagem recebe +4 de bônus nas jogadas de dano dos ataques corpo a corpo, nos testes de Atletismo e nos testes de Tolerância até o final do encontro ou até que não esteja mais sangrando. Especial: Se o guerreiro for um draconato, o bônus aumenta para +5.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Entrincheirar-se", Edition: "4e", ClassID: &id,
			Description: "Você assume uma postura defensiva, erguendo o escudo para se proteger.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Special: "Condição: O guerreiro deve empunhar um escudo.",
			Effect:  "Enquanto adotar esta postura, o guerreiro fica lento, mas obtém cobertura contra todos os ataques. O personagem pode encerrar esta postura usando uma ação livre.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Flagelo do Atirador", Edition: "4e", ClassID: &id,
			Description: "O fato de seu inimigo ser muito covarde para se aproximar em combate corpo a corpo aumenta a sua confiança.",
			Keywords: "Cura, Marcial", ActionType: "Reação Imediata", Range: "Pessoal",
			Special: "Gatilho: O guerreiro é atingido por um ataque à distância.",
			Effect:  "O personagem gasta um pulso de cura e recupera pontos de vida adicionais iguais ao dobro do seu mod Sabedoria.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Postura Ameaçadora", Edition: "4e", ClassID: &id,
			Description: "Você aparenta estar sempre pronto para atacar, forçando os oponentes marcados a dedicar ainda mais atenção a você.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto o guerreiro adotar esta postura, sempre que um inimigo marcado pelo personagem realizar um ataque que não inclua o guerreiro como alvo, este ataque concede vantagem de combate ao guerreiro e seus aliados até o começo do próximo turno do personagem.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Ressurgimento Defensivo", Edition: "4e", ClassID: &id,
			Description: "Você resiste à pressão e redobra seus esforços defensivos.",
			Keywords: "Cura, Marcial", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "O guerreiro pode gastar um pulso de cura. Até o começo do seu próximo turno, ele recebe um bônus na CA igual ao seu mod Destreza.",
			PowerType: domain.PowerDaily, Level: 10,
		},

		// ── POR ENCONTRO DE NÍVEL 13 ───────────────────────────────
		{
			Name: "Balanço Dispersivo", Edition: "4e", ClassID: &id,
			Description: "Você gira sua arma num movimento amplo e os inimigos que não foram surpreendidos têm que sair do caminho.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. CA",
			Hit:  "2[A] + mod Força de dano e o alvo é conduzido 1 quadrado.",
			Miss: "O alvo é empurrado 1 quadrado.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Dança das Lâminas", Edition: "4e", ClassID: &id,
			Description: "Você se desloca entre dois inimigos, conduzindo-os de um lado para outro com seus ataques.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura (alvo primário)", Attack: "Força vs. CA (arma principal)",
			Hit:    "1[A] + mod Força de dano e o alvo é conduzido 2 quadrados. Se o guerreiro tiver vantagem de combate contra o alvo primário, o ataque causa dano adicional igual ao mod Destreza.",
			Effect: "O personagem ajusta 3 quadrados e realiza um ataque secundário. Alvo Secundário: Uma criatura diferente do alvo primário. Ataque Secundário: Força vs. CA (mão inábil). Sucesso: 1[A] + mod Força de dano e o alvo é conduzido 2 quadrados; se vantagem de combate contra o alvo secundário, dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Estridor Pavoroso", Edition: "4e", ClassID: &id,
			Description: "Os inimigos próximos ficam tão chocados com seu ataque impiedoso que passam a considerá-lo o oponente mais perigoso no campo de batalha.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "3[A] + mod Força de dano e os inimigos que estiverem adjacentes ao alvo ficam marcados até o final do próximo turno do guerreiro.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, os inimigos a até 2 quadrados do alvo ficam marcados até o final do próximo turno.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Golpe Garantido", Edition: "4e", ClassID: &id,
			Description: "Você explora o ponto fraco do inimigo, direcionando sua arma com uma força surpreendente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura contra a qual o guerreiro tem vantagem de combate", Attack: "Força vs. Reflexos",
			Hit:     "3[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma lâmina leve ou lâmina pesada, o ataque causa dano adicional igual ao mod Destreza. Especial: Se o guerreiro for um halfling, ele não precisa de vantagem de combate contra o alvo.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Pancada Contundente", Edition: "4e", ClassID: &id,
			Description: "Com um urro e uma pancada poderosa, você empurra o inimigo para trás, derrubando-o.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano e o alvo é empurrado 2 quadrados e fica derrubado.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Reprimenda Brutal", Edition: "4e", ClassID: &id,
			Description: "Ao atacar seu companheiro, o adversário atrai a ira virtuosa.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA. Se o alvo atacou o guerreiro ou um aliado desde o final do último turno do personagem, este recebe +2 de bônus na jogada de ataque.",
			Hit:     "2[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça ou picareta, o ataque causa dano adicional igual ao mod Constituição. Especial: Quando realizar um ataque de oportunidade, o personagem pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 13,
		},

		// ── DIÁRIAS DE NÍVEL 15 ────────────────────────────────────
		{
			Name: "Carvar Iniciais", Edition: "4e", ClassID: &id,
			Description: "Você faz um corte profundo, deixando uma marca significativa.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma lâmina leve.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit: "4[A] + mod Força de dano e o alvo fica marcado até o final do encontro ou até ficar inconsciente. Nenhuma outra marca pode substituir essa marca.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Gambito do Defensor", Edition: "4e", ClassID: &id,
			Description: "Incitando um ataque, você faz com que o inimigo baixe a guarda, deixando-a aberta para um contra-ataque.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Vontade",
			Hit:    "Até o final do turno do guerreiro, ele recebe um bônus de poder nas jogadas de dano dos ataques corpo a corpo contra o alvo igual ao seu mod Sabedoria.",
			Effect: "O alvo pode realizar um ataque básico contra o guerreiro usando uma reação imediata. Se fizer isso, o personagem realiza um ataque secundário contra o alvo usando uma ação livre. Ataque Secundário: Força vs. CA. Sucesso: 5[A] + mod Força de dano. Fracasso: Metade do dano.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Impulso do Matador", Edition: "4e", ClassID: &id,
			Description: "Farejando o sangue, você avança para liquidar seu inimigo.",
			Keywords: "Arma, Marcial", ActionType: "Reação Imediata", Range: "Corpo a corpo 1",
			Special: "Gatilho: Um inimigo a até 5 quadrados fica sangrando.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Effect:  "Antes do ataque, o guerreiro percorre seu deslocamento.",
			Hit:     "3[A] + mod Força de dano e o alvo fica marcado (TR encerra). Se já estiver marcado pelo guerreiro, o ataque causa dano adicional igual ao mod Sabedoria do personagem.",
			Special2: "Especial: Se o guerreiro for um elfo, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Investida Rochosa", Edition: "4e", ClassID: &id,
			Description: "Você e sua lâmina se assemelham a uma avalanche de pedras descendo a montanha, esmagando qualquer um tolo o bastante para permanecer em seu caminho.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve realizar uma investida e usar este poder no lugar de um ataque básico corpo a corpo. Durante a investida, pode se mover por quadrados ocupados por inimigos, mas deve encerrar seu movimento num espaço desocupado.",
			Target:  "Uma criatura e os inimigos nos espaços ingressados pelo guerreiro", Attack: "Força vs. CA, um ataque por alvo",
			Hit:     "2[A] + mod Força de dano e o alvo é empurrado 2 quadrados e fica derrubado.",
			Special2: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			Miss:    "O alvo é empurrado 1 quadrado.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Postura Fluente", Edition: "4e", ClassID: &id,
			Description: "Como um metal líquido, você flui para onde a batalha o levar.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, usando uma ação de movimento, o guerreiro pode ajustar 1 quadrado (ou 2 quadrados se não estiver vestindo uma armadura pesada) e realizar um ataque básico corpo a corpo. Se tiver vantagem de combate contra o alvo ou obtiver sucesso no ataque, o ataque causa dano adicional igual ao mod Sabedoria do personagem.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Ventania de Aço", Edition: "4e", ClassID: &id,
			Description: "Você atravessa as fileiras de oponentes como se fosse um vento impetuoso.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma lâmina leve ou lâmina pesada, o ataque causa dano adicional igual ao mod Destreza.",
			Effect:  "O guerreiro ajusta 1 quadrado e repete o ataque contra um inimigo que não foi atingido pelo primeiro ataque.",
			PowerType: domain.PowerDaily, Level: 15,
		},

		// ── UTILITÁRIAS DE NÍVEL 16 ────────────────────────────────
		{
			Name: "Grito Reinante", Edition: "4e", ClassID: &id,
			Description: "Seu grito de batalha abala os nervos dos inimigos, atraindo a atenção deles em sua direção.",
			Keywords: "Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 3",
			Target: "Os inimigos dentro da explosão",
			Effect: "O guerreiro recebe +1 de bônus de poder nas jogadas de ataque contra o alvo, que também fica marcado (TR encerra ambos).",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Montanha Imóvel", Edition: "4e", ClassID: &id,
			Description: "Você finca os pés no chão, recusando-se a se mover.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, se for puxado, empurrado ou conduzido, mas não se mover mais que 2 quadrados desde o começo do seu último turno, reduza o movimento forçado em 2 quadrados. Especial: Se o guerreiro for um anão, reduza o movimento forçado em 5 quadrados.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Postura de Marcação", Edition: "4e", ClassID: &id,
			Description: "Apenas sua presença é o suficiente para baixar a guarda de seus adversários.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Special: "Pré-requisito: O guerreiro deve ser treinado em Intimidação.",
			Effect:  "Enquanto adotar esta postura, qualquer inimigo que começar o turno num quadrado adjacente ao personagem fica marcado até o começo do próximo turno do personagem.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Travessia de Gigante", Edition: "4e", ClassID: &id,
			Description: "Você atravessa o caos da batalha como um colosso, indiferente aos inimigos ao seu redor.",
			Keywords: "Marcial", ActionType: "Ação de Movimento", Range: "Pessoal",
			Effect: "O guerreiro ajusta um número de quadrados igual ao seu deslocamento. Durante o ajuste, ignora terrenos acidentados e pode se mover por quadrados ocupados, contanto que termine o deslocamento num espaço desocupado.",
			PowerType: domain.PowerEncounter, Level: 16,
		},
		{
			Name: "Travessia Estimulante", Edition: "4e", ClassID: &id,
			Description: "Você corre para ficar ao lado de seu aliado, pronto para defendê-lo.",
			Keywords: "Marcial", ActionType: "Ação de Movimento", Range: "Pessoal",
			Effect: "O guerreiro percorre seu deslocamento, terminando num espaço adjacente a um aliado. O personagem recebe um número de pontos de vida temporários igual a 2d8 + mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 16,
		},

		// ── POR ENCONTRO DE NÍVEL 17 ───────────────────────────────
		{
			Name: "Acometida do Guerrilheiro", Edition: "4e", ClassID: &id,
			Description: "Você salta para frente, golpeando um oponente e usando o movimento para derrubar o outro.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura (alvo primário)", Attack: "Força vs. CA (ataque primário)",
			Hit:     "2[A] + mod Força de dano e o guerreiro ajusta 2 quadrados e realiza um ataque secundário. Se tiver vantagem de combate contra o alvo primário, o ataque primário causa dano adicional igual ao mod Destreza.",
			Effect:  "Alvo Secundário: Uma criatura diferente do alvo primário. Ataque Secundário: Força vs. CA. Sucesso: 1[A] + mod Força de dano; se vantagem de combate contra o alvo secundário, dano adicional igual ao mod Destreza.",
			Special: "Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Golpe e Contragolpe", Edition: "4e", ClassID: &id,
			Description: "Você golpeia o oponente e apesar de não atingi-lo com toda a sua força, você mantém a atenção dele em você.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. Fortitude",
			Hit:    "1[A] + mod Força de dano. Se antes do próximo turno do personagem o alvo realizar um ataque que não inclua o guerreiro como alvo, ele pode ajustar 1 quadrado e realizar um ataque secundário com a arma da mão inábil contra ele, usando uma interrupção imediata.",
			Effect: "Ataque Secundário: Força + 2 vs. CA. Sucesso: 3[A] + mod Força de dano.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Golpe Selvagem", Edition: "4e", ClassID: &id,
			Description: "Abandonando qualquer tipo de proteção, você se lança furiosamente contra o oponente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "4[A] + mod Força de dano e o personagem concede vantagem de combate a todos os inimigos até o começo do seu próximo turno.",
			Special: "Especial: Se o guerreiro for um humano, o ataque causa dano adicional igual ao mod Sabedoria. Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Pancada Tremulante", Edition: "4e", ClassID: &id,
			Description: "Seu golpe sólido faz com que o oponente momentaneamente perca a capacidade de raciocinar.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "3[A] + mod Força de dano e o alvo sofre -2 de penalidade nas jogadas de ataque até o final do seu próximo turno.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça ou martelo, o ataque causa dano adicional igual ao mod Constituição e o alvo fica pasmo até o final do próximo turno do personagem.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Rajada Condutora", Edition: "4e", ClassID: &id,
			Description: "Você empurra o oponente para trás com uma série de firmes estocadas, aproveitando a abertura em suas defesas para escapar.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "2[A] + mod Força de dano e o alvo é empurrado 2 quadrados. O guerreiro ajusta 2 quadrados.",
			Special: "Arma: Se o guerreiro estiver empunhando uma lâmina leve ou lâmina pesada, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Torque Turbulento", Edition: "4e", ClassID: &id,
			Description: "Seu corpo e arma giram como um só, golpeando e derrubando os inimigos que não saírem do seu caminho.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. CA",
			Hit:     "1[A] + mod Força de dano e, até o começo do próximo turno do guerreiro, qualquer inimigo que ingressar num quadrado adjacente ao personagem fica marcado até o final do próximo turno do guerreiro e sofre 5 de dano.",
			Special2: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 17,
		},

		// ── DIÁRIAS DE NÍVEL 19 ────────────────────────────────────
		{
			Name: "Agressor Incansável", Edition: "4e", ClassID: &id,
			Description: "Você se anima ao surrar um oponente.",
			Keywords: "Arma, Confiável, Cura, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit: "4[A] + mod Força de dano e o personagem pode gastar um pulso de cura.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Esmagar e Agarrar", Edition: "4e", ClassID: &id,
			Description: "Seu golpe estontante distrai o inimigo tempo o bastante para que você consiga agarrá-lo.",
			Keywords: "Arma, Confiável, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve ter uma mão livre.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit:    "3[A] + mod Força de dano e o alvo é agarrado.",
			Effect: "Quando o personagem sustenta este poder, o alvo sofre 1[A] + mod Força de dano.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Estocada Controlada", Edition: "4e", ClassID: &id,
			Description: "Após uma estocada cruel, você habilmente encurrala seu oponente com sua arma de haste.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de haste ou uma lança. Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA (ataque primário)",
			Hit:  "4[A] + mod Força de dano e o alvo fica marcado (TR encerra).",
			Miss: "Metade do dano e o alvo fica marcado até o final do próximo turno.",
			Effect: "Antes do final do próximo turno do guerreiro, se o alvo realizar uma ação de movimento enquanto estiver dentro do alcance da arma do personagem, este realiza um ataque secundário contra o alvo usando uma interrupção imediata. Ataque Secundário: Força vs. CA. Sucesso: 2[A] + mod Força de dano e a ação de movimento do alvo é cancelada.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Rasteira Protetora", Edition: "4e", ClassID: &id,
			Description: "Você gira a arma cuidadosamente ao seu redor, assumindo uma postura defensiva.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "As criaturas dentro da explosão e na linha de visão", Attack: "Força vs. CA",
			Hit:     "3[A] + mod Força de dano.",
			Miss:    "Metade do dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma lâmina pesada ou mangual, o ataque causa dano adicional igual ao mod Destreza.",
			Effect:  "O personagem recebe +4 de bônus na CA até o começo do seu próximo turno.",
			PowerType: domain.PowerDaily, Level: 19,
		},

		// ── UTILITÁRIAS DE NÍVEL 22 ────────────────────────────────
		{
			Name: "Irredutível", Edition: "4e", ClassID: &id,
			Description: "A dor só o estimula a realizar grandes façanhas de heroísmo.",
			Keywords: "Cura, Marcial", ActionType: "Reação Imediata", Range: "Pessoal",
			Special: "Gatilho: O guerreiro é atingido por um ataque.",
			Effect:  "O personagem gasta dois pulsos de cura e recupera seu valor máximo de pontos de vida. Especial: Se o guerreiro for um draconato, recebe +1 de bônus de poder nas jogadas de ataque e em todas as defesas até o final do próximo turno.",
			PowerType: domain.PowerDaily, Level: 22,
		},
		{
			Name: "Postura do Vencedor", Edition: "4e", ClassID: &id,
			Description: "Você se sente vigoroso e confiante sempre que derruba um inimigo.",
			Keywords: "Cura, Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, sempre que reduzir um inimigo a 0 ponto de vida ou menos, usando uma ação livre, o guerreiro pode gastar um pulso de cura, realizar um teste de resistência ou outras ações. O personagem recebe um bônus nos testes de resistência igual ao seu mod Sabedoria.",
			PowerType: domain.PowerDaily, Level: 22,
		},
		{
			Name: "Postura Inabalável", Edition: "4e", ClassID: &id,
			Description: "Permanecendo firme, você não permite que nada lhe cause hesitação.",
			Keywords: "Marcial, Postura", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Enquanto adotar esta postura, sempre que sofrer um efeito que pode ser encerrado por um teste de resistência, o guerreiro pode realizar um teste de resistência contra esse efeito usando uma reação imediata.",
			PowerType: domain.PowerDaily, Level: 22,
		},
		{
			Name: "Ressurgimento Inspirado", Edition: "4e", ClassID: &id,
			Description: "Entusiasmado com o sucesso, você retoma o fôlego e se desloca a próximo ataque.",
			Keywords: "Cura, Marcial", ActionType: "Ação Livre", Range: "Pessoal",
			Special: "Gatilho: Um inimigo marcado pelo guerreiro é reduzido a 0 ponto de vida ou menos.",
			Effect:  "O personagem gasta um pulso de cura e ajusta 3 quadrados.",
			PowerType: domain.PowerEncounter, Level: 22,
		},
		{
			Name: "Uivo Desafiador", Edition: "4e", ClassID: &id,
			Description: "Você responde à dor com um grito corajoso e uma vigilância furiosa.",
			Keywords: "Marcial, Medo", ActionType: "Reação Imediata", Range: "Explosão contígua 5",
			Special: "Gatilho: O guerreiro sofre dano de um ataque corpo a corpo.",
			Target:  "Os inimigos dentro da explosão e na linha de visão",
			Effect:  "O alvo fica marcado até o final do encontro, até o guerreiro ficar inconsciente ou até que a marca seja substituída. Enquanto marcado, o alvo concede vantagem de combate ao personagem.",
			PowerType: domain.PowerDaily, Level: 22,
		},

		// ── POR ENCONTRO DE NÍVEL 23 ───────────────────────────────
		{
			Name: "Engodo do Mestre de Armas", Edition: "4e", ClassID: &id,
			Description: "Você realiza um ataque transitório tirando o equilíbrio do oponente. Com um empurrão você o joga para longe enquanto troca de posição com ele.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA (arma principal e arma da mão inábil), dois ataques",
			Hit:    "2[A] + mod Força de dano por ataque. Se obtiver sucesso em um dos ataques, o personagem pode trocar de lugar com o alvo. Se obtiver sucesso nos dois ataques, o personagem pode trocar de lugar com o alvo e o alvo é conduzido 3 quadrados.",
			Effect: "Se o guerreiro tiver vantagem de combate contra o alvo, cada ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Machado Esmagador", Edition: "4e", ClassID: &id,
			Description: "Girando por todos os lados, você golpeia com ímpeto cada um dos adversários.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. CA. O guerreiro recebe +1 de bônus cumulativo nas jogadas de ataque para cada alvo depois do primeiro.",
			Hit:     "2[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando um machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Martelo Angustiante", Edition: "4e", ClassID: &id,
			Description: "Sua arma golpeia o adversário, forçando os inimigos próximos a reconhecer a ameaça que você representa.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de duas mãos.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit:     "4[A] + mod Força de dano e os inimigos adjacentes ao alvo ficam marcados até o começo do próximo turno do personagem.",
			Special2: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Pancada Incapacitante", Edition: "4e", ClassID: &id,
			Description: "Você surra seu oponente violentamente, impedindo-o de se mover.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit:     "1[A] + mod Força de dano e o alvo fica lento e enfraquecido até o final do próximo turno do personagem.",
			Special2: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque causa dano adicional igual ao mod Constituição e o alvo fica derrubado.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Punhalada Meticulosa", Edition: "4e", ClassID: &id,
			Description: "Sua precisão o permite golpear contra um pequeno orifício na armadura do oponente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Reflexos",
			Hit:     "3[A] + mod Força de dano.",
			Special: "Arma: Se o guerreiro estiver empunhando uma lâmina leve ou lança, o ataque causa dano adicional igual ao mod Destreza. Especial: Quando realizar um ataque de oportunidade, o personagem pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Resposta Reversa", Edition: "4e", ClassID: &id,
			Description: "Você realiza um bloqueio rápido para proteger um aliado, realiza uma hábil estocada e assume uma nova posição.",
			Keywords: "Arma, Marcial", ActionType: "Interrupção Imediata", Range: "Corpo a corpo 1",
			Special: "Gatilho: Um inimigo adjacente atinge um aliado do guerreiro com um ataque corpo a corpo.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit:    "2[A] + mod Força de dano e o guerreiro ajusta 2 quadrados, contanto que termine o deslocamento adjacente ao alvo.",
			Effect: "O aliado sofre apenas metade do dano do ataque que ativou o gatilho.",
			PowerType: domain.PowerEncounter, Level: 23,
		},

		// ── DIÁRIAS DE NÍVEL 25 ────────────────────────────────────
		{
			Name: "Explosão de Marcação", Edition: "4e", ClassID: &id,
			Description: "Com uma rajada de ataques precisos, você fere os adversários próximos, mostrando que essa luta terminará mal se eles não forem capazes de derrotá-lo rapidamente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. Reflexos",
			Hit:     "4[A] + mod Força de dano. Se o guerreiro tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			Miss:    "Metade do dano.",
			Effect:  "O alvo fica marcado até o final do encontro, até o guerreiro ficar inconsciente ou até que a marca seja substituída.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Investida da Balista", Edition: "4e", ClassID: &id,
			Description: "Como uma seta disparada de uma balista, você avança violentamente, trespassando os oponentes.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA (ataque primário)",
			Hit:     "3[A] + mod Força de dano e o alvo fica imobilizado (TR encerra).",
			Special: "Arma: Se o guerreiro estiver empunhando uma lança, o alvo fica pasmo em vez de imobilizado (TR encerra).",
			Effect:  "O guerreiro realiza um ataque secundário contra o alvo. Ataque Secundário: Destreza vs. Fortitude. Sucesso: 2[A] + mod Destreza de dano e o alvo fica derrubado.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Massacre Implacável", Edition: "4e", ClassID: &id,
			Description: "Sem misericórdia você massacra o oponente em desvantagem, provocando os demais inimigos.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura sangrando ou caída", Attack: "Força + 2 vs. CA",
			Hit:    "6[A] + mod Força de dano.",
			Effect: "Os inimigos a até 3 quadrados do guerreiro, exceto o alvo, ficam marcados até o final do próximo turno do personagem. Se o ataque reduzir o alvo a 0 ponto de vida ou menos, em vez disso, os inimigos ficam marcados até o final do encontro, até o guerreiro ficar inconsciente ou até que a marca seja substituída.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Pancada e Terremoto", Edition: "4e", ClassID: &id,
			Description: "Com um golpe estrondoso você derruba seu adversário e envia ondas de choque pela terra. Essas ondas lançam os demais inimigos para longe.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura (alvo primário)", Attack: "Força vs. CA (ataque primário)",
			Hit:     "3[A] + mod Força de dano e o alvo fica derrubado e pasmo até o final do próximo turno do guerreiro. O personagem realiza um ataque secundário.",
			Special: "Arma: Se o guerreiro estiver empunhando uma maça, machado ou martelo, o ataque primário causa dano adicional igual ao mod Constituição.",
			Effect:  "Alvo Secundário: Os inimigos a até 2 quadrados do alvo primário. Ataque Secundário: Força vs. Fortitude. Sucesso: Mod Força de dano e o alvo secundário fica derrubado.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Provocação Sobrepujante", Edition: "4e", ClassID: &id,
			Description: "Seu ataque hábil e impiedoso fere carne e confiança, fornecendo a você uma vantagem duradoura contra o inimigo.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:    "6[A] + mod Força de dano.",
			Miss:   "Metade do dano.",
			Effect: "O alvo fica marcado até o final do encontro, até o guerreiro ficar inconsciente ou até que a marca seja substituída. Enquanto marcado, o alvo concede vantagem de combate ao personagem.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Ressurgimento do Guerreiro", Edition: "4e", ClassID: &id,
			Description: "Você brutaliza o inimigo e se sente revigorado por sua bravura.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força + 2 vs. CA",
			Hit:    "5[A] + mod Força de dano.",
			Effect: "Se já tiver utilizado todos os seus poderes de ataque por encontro, o guerreiro recupera a utilização de um poder de ataque por encontro que tenha usado durante este encontro.",
			PowerType: domain.PowerDaily, Level: 25,
		},

		// ── POR ENCONTRO DE NÍVEL 27 ───────────────────────────────
		{
			Name: "Avanço Sangrento", Edition: "4e", ClassID: &id,
			Description: "Tomado por uma sede de sangue, você salta para o centro da batalha.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "4[A] + mod Força de dano.",
			Special: "Arma: Se o alvo estiver sangrando, o ataque causa dano adicional igual ao mod Constituição do guerreiro. Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Golpe Desesperado", Edition: "4e", ClassID: &id,
			Description: "Você ataca com selvageria, ansioso para acabar com o oponente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit:     "5[A] + mod Força de dano e o alvo sofre -2 de penalidade nas jogadas de ataque até o final do próximo turno do personagem.",
			Special: "Especial: Se o guerreiro for um humano, o ataque causa dano adicional igual ao mod Sabedoria.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Golpe Giratório Mortal", Edition: "4e", ClassID: &id,
			Description: "Você realiza um golpe cortante para a frente e gira sua arma num arco mortal.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de duas mãos.",
			Target:  "Uma criatura (alvo primário)", Attack: "Força vs. CA (ataque primário)",
			Hit:    "2[A] + mod Força de dano. O personagem realiza um ataque secundário.",
			Effect: "Alvo Secundário: Os inimigos a até 1 quadrado. Ataque Secundário: Força vs. CA. Sucesso: 1[A] + mod Força + mod Destreza de dano.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Recompensa do Covarde", Edition: "4e", ClassID: &id,
			Description: "Você lança sua arma contra um oponente recuando, fazendo-o vacilar enquanto ele tenta fugir.",
			Keywords: "Marcial", ActionType: "Reação Imediata", Range: "À distância 5",
			Special: "Gatilho: Um inimigo marcado pelo guerreiro deixa um quadrado adjacente. Condição: O guerreiro deve empunhar uma arma de combate corpo a corpo.",
			Target:  "O inimigo que ativou o gatilho", Attack: "Força vs. CA",
			Hit:    "2[A] + mod Força de dano e o alvo fica imobilizado até o final do próximo turno do guerreiro.",
			Effect: "A arma cai num quadrado (à escolha do personagem) adjacente ao alvo.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Supremacia com Duas Armas", Edition: "4e", ClassID: &id,
			Description: "Você atinge dois ataques cruéis contra o inimigo, ganhando confiança como prova de seu estilo de luta superior.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar duas armas de combate corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA (arma principal e arma da mão inábil), dois ataques",
			Hit:    "2[A] + mod Força de dano por ataque.",
			Effect: "Se o personagem obtiver sucesso nos dois ataques, ele concede vantagem de combate ao personagem contra o alvo até o final do próximo turno do guerreiro.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Torrente de Punhaladas", Edition: "4e", ClassID: &id,
			Description: "Você se enfurece como uma nuvem tempestuosa, desferindo diversos golpes contra os inimigos tolos o bastante para permanecerem ao seu lado.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Special: "Condição: O guerreiro deve empunhar uma lâmina leve.",
			Target:  "Os inimigos dentro da explosão e na linha de visão", Attack: "Força vs. CA",
			Hit:     "1[A] + mod Força de dano. Se estiver empunhando duas armas de combate corpo a corpo, o guerreiro pode atacar cada alvo com sua arma principal e sua arma da mão inábil.",
			Special2: "Se o guerreiro tiver vantagem de combate contra o alvo, o ataque causa dano adicional igual ao mod Destreza.",
			PowerType: domain.PowerEncounter, Level: 27,
		},

		// ── DIÁRIAS DE NÍVEL 29 ────────────────────────────────────
		{
			Name: "Avalanche de Aço", Edition: "4e", ClassID: &id,
			Description: "Você se choca contra o inimigo com a fúria impiedosa de um deslizamento, permitindo que sua arma seja seu guia e ignorando tudo, exceto seu oponente.",
			Keywords: "Arma, Marcial, Revigorante", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de duas mãos. Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. CA",
			Hit:    "8[A] + mod Força de dano.",
			Miss:   "Metade do dano.",
			Effect: "O guerreiro concede vantagem de combate a todos os inimigos até o começo do seu próximo turno.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Ferimento Mortal", Edition: "4e", ClassID: &id,
			Description: "Você perfura o oponente, liberando muito sangue do ferimento.",
			Keywords: "Arma, Confiável, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA",
			Hit: "3[A] + mod Força de dano e 20 de dano contínuo (TR encerra). Enquanto estiver sofrendo este dano contínuo, o alvo sofre -2 de penalidade nos testes de resistência.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Martelo Titânico", Edition: "4e", ClassID: &id,
			Description: "Seu golpe atinge com uma força impiedosa, aturdindo os sentidos de seu oponente.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Especial: Quando realizar uma investida, o guerreiro pode usar este poder no lugar de um ataque básico corpo a corpo.",
			Target:  "Uma criatura", Attack: "Força vs. Fortitude",
			Hit:      "3[A] + mod Força de dano e o alvo fica atordoado (TR encerra).",
			Special2: "Arma: Se o guerreiro estiver empunhando um martelo, o ataque causa dano adicional igual ao mod Constituição.",
			Miss:     "Metade do dano e o alvo fica pasmo (TR encerra).",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Pancada Progressiva", Edition: "4e", ClassID: &id,
			Description: "O ímpeto de seu ataque lança um inimigo de encontro ao outro.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Special: "Condição: O guerreiro deve empunhar uma arma de duas mãos.",
			Target:  "Uma criatura (alvo primário)", Attack: "Força vs. Fortitude (ataque primário)",
			Hit:    "4[A] + mod Força de dano e o alvo é empurrado um número de quadrados igual a 1 + mod Constituição do guerreiro e fica derrubado. O personagem realiza um ataque secundário.",
			Effect: "Alvo Secundário: Uma criatura adjacente ao alvo primário. Ataque Secundário: Força vs. Fortitude. Sucesso: 1d10 + mod Força de dano e o alvo secundário é empurrado 2 quadrados e fica derrubado; o personagem repete o ataque secundário contra uma criatura adjacente ao alvo secundário.",
			Miss:   "Metade do dano, o alvo é empurrado 1 quadrado e o guerreiro não realiza o ataque secundário.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Rajada Catastrófica", Edition: "4e", ClassID: &id,
			Description: "Você se torna uma tempestade de violência, lançando ataques impetuosos e velozes como raios.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. CA, três ataques",
			Hit:  "2[A] + mod Força de dano por ataque. Se obtiver sucesso em dois ataques, o guerreiro causa 1d10 de dano adicional. Se obtiver sucesso nos três ataques, em vez disso, causa 2d10 de dano adicional.",
			Miss: "Metade do dano por ataque.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Tempestade de Lâminas", Edition: "4e", ClassID: &id,
			Description: "Você avança por entre os inimigos com a arma brilhando enquanto golpeia por suas fileiras.",
			Keywords: "Arma, Marcial", ActionType: "Ação Padrão", Range: "Arma corpo a corpo",
			Target: "Uma criatura", Attack: "Força vs. Reflexos",
			Hit:    "3[A] + mod Força + mod Destreza de dano e o alvo fica pasmo (TR encerra).",
			Miss:   "Metade do dano e o alvo não fica pasmo.",
			Effect: "O guerreiro ajusta 3 quadrados e repete o ataque contra um segundo alvo. Depois, ajusta mais 3 quadrados e repete o ataque contra um terceiro alvo.",
			PowerType: domain.PowerDaily, Level: 29,
		},
	}
	for _, s := range skills {
		upsertSkill(db, s, id)
	}
	log.Println("  ✓ Guerreiro 4e (Poder Marcial): poderes seedados")
}

func seedLadinoSkillsPoderMarcial(db *gorm.DB) {
	var cls domain.Class
	if err := db.Where("name = ? AND edition = ?", "Ladino", "4e").First(&cls).Error; err != nil {
		log.Println("  ✗ Ladino 4e não encontrado")
		return
	}
	id := cls.ID

	skills := []domain.Skill{}
	for _, s := range skills {
		upsertSkill(db, s, id)
	}
	log.Println("  ✓ Ladino 4e (Poder Marcial): poderes seedados")
}

func seedPatrulheiroSkillsPoderMarcial(db *gorm.DB) {
	var cls domain.Class
	if err := db.Where("name = ? AND edition = ?", "Patrulheiro", "4e").First(&cls).Error; err != nil {
		log.Println("  ✗ Patrulheiro 4e não encontrado")
		return
	}
	id := cls.ID

	skills := []domain.Skill{}
	for _, s := range skills {
		upsertSkill(db, s, id)
	}
	log.Println("  ✓ Patrulheiro 4e (Poder Marcial): poderes seedados")
}
