package seed

import (
	"log"
	"rpg-manager/internal/domain"

	"gorm.io/gorm"
)

// seedRituais4e semeia o catálogo de Rituais de D&D 4e — Livro do Jogador 1
// (Capítulo 10, "Rituais", p.296-317, 49 rituais) e os rituais novos do
// Livro do Jogador 2 (Capítulo 3, "Opções de Personagens", p.211-217, 23
// rituais). O Livro do Jogador 3 não acrescenta nenhum ritual (confirmado
// por varredura completa do PDF, sem nenhuma seção "Descrições dos
// Rituais"/"Rituais por Nível" como as dos outros dois livros).
//
// Todos os campos vêm de extração direta do texto real dos PDFs (não de
// suposição genérica sobre rituais de D&D 4e) — ver o levantamento
// aprovado pelo usuário antes desta implementação. Dois rituais do LJ2
// (Canção do Sustento, Refrão da Verdade) têm ComponentCost/MarketPrice
// vazios porque o layout em duas colunas do PDF misturou os valores desses
// dois rituais com os de um item mágico vizinho na mesma página, tornando
// o preço exato ambíguo na extração — marcado explicitamente na
// Description em vez de inventado.
type ritualSeed struct {
	Name, Category, KeySkill, ComponentCost, MarketPrice, Prerequisite, SourceBook, Description string
	Level                                                                                        int
}

func seedRituais4e(db *gorm.DB) {
	rituais := []ritualSeed{
		// ── Livro do Jogador 1, Capítulo 10 (49 rituais) ──────────────────
		{Name: "Arrombar", Level: 4, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "35 PO, mais 1 pulso de cura", MarketPrice: "175 PO", SourceBook: "Livro do Jogador 1", Description: "Abre uma única porta, baú, portão ou outro objeto, funcionando até contra portais selados pelo ritual Tranca Arcana."},
		{Name: "Banquete dos Viajantes", Level: 4, Category: "Exploração", KeySkill: "Natureza (sem teste)", ComponentCost: "35 PO", MarketPrice: "175 PO", SourceBook: "Livro do Jogador 1", Description: "Cria água e comida suficientes para alimentar cinco criaturas Médias/Pequenas ou duas Grandes durante 24 horas."},
		{Name: "Barganha do Mestre do Conhecimento", Level: 22, Category: "Adivinhação", KeySkill: "Religião", ComponentCost: "13.000 PO", MarketPrice: "65.000 PO", SourceBook: "Livro do Jogador 1", Description: "Concede uma breve audiência mágica com uma entidade poderosa que possui a informação buscada, mediante uma oferenda valiosa."},
		{Name: "Baú Secreto de Leomund", Level: 6, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "140 PO, mais um foco no valor de 200 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Cria um baú extradimensional selado com símbolos arcanos e um objeto de significado pessoal do dono, guardável em qualquer lugar."},
		{Name: "Boca Encantada", Level: 1, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Vincula uma mensagem a uma superfície; quando as condições impostas forem satisfeitas, ela manifesta uma boca e transmite a mensagem."},
		{Name: "Caminhar na Água", Level: 2, Category: "Exploração", KeySkill: "Natureza (sem teste)", ComponentCost: "20 PO", MarketPrice: "100 PO", SourceBook: "Livro do Jogador 1", Description: "Permite que o personagem ou um aliado se desloque sobre a água como se fosse terra firme."},
		{Name: "Caminhar nas Sombras", Level: 12, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "500 PO", MarketPrice: "2.600 PO", SourceBook: "Livro do Jogador 1", Description: "O personagem e seus aliados viajam pela Umbra, multiplicando seu deslocamento básico de viagem por 5 pela duração do ritual."},
		{Name: "Círculo Mágico", Level: 5, Category: "Contenção", KeySkill: "Arcanismo", ComponentCost: "100 PO", MarketPrice: "250 PO", SourceBook: "Livro do Jogador 1", Description: "Desenha um círculo de símbolos arcanos de proteção que dificulta o ingresso de criaturas de uma origem ou tipo escolhido."},
		{Name: "Compreender Idioma", Level: 1, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Permite compreender um idioma ouvido ou uma amostra de escrita vislumbrada nas últimas 24 horas."},
		{Name: "Comunhão com a Natureza", Level: 6, Category: "Adivinhação", KeySkill: "Natureza", ComponentCost: "140 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Comungando com os espíritos da terra, revela informações sobre o entorno imediato através de um número de perguntas."},
		{Name: "Consertar", Level: 1, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "Especial (20% do preço do item)", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Repara completamente um único objeto que caiba em um cubo de 3 metros de lado."},
		{Name: "Consultar o Oráculo", Level: 16, Category: "Adivinhação", KeySkill: "Religião", ComponentCost: "3.600 PO", MarketPrice: "9.000 PO", SourceBook: "Livro do Jogador 1", Description: "Invoca um espírito oracular do espaço entre os planos, capaz de testemunhar eventos e responder perguntas."},
		{Name: "Consultar os Sábios Místicos", Level: 10, Category: "Adivinhação", KeySkill: "Religião", ComponentCost: "400 PO", MarketPrice: "1.000 PO", SourceBook: "Livro do Jogador 1", Description: "Faz uma única pergunta a presenças extraplanares, usando um teste de Religião com +10 de bônus no lugar de Arcanismo ou História."},
		{Name: "Criar Passagens", Level: 12, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "1.000 PO", MarketPrice: "2.600 PO", SourceBook: "Livro do Jogador 1", Description: "Abre uma passagem através de qualquer material sólido, com profundidade determinada pelo resultado do teste de Arcanismo."},
		{Name: "Criatura Ilusória", Level: 12, Category: "Enganação", KeySkill: "Arcanismo", ComponentCost: "500 PO", MarketPrice: "2.600 PO", SourceBook: "Livro do Jogador 1", Description: "Cria a ilusão de uma única criatura de tamanho Pequeno a Grande, capaz de se mover e agir em sequências programadas."},
		{Name: "Curar Doença", Level: 6, Category: "Restauração", KeySkill: "Cura", ComponentCost: "150 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Elimina uma única moléstia que esteja afligindo o alvo, ativa ou em incubação, removendo todos os efeitos negativos."},
		{Name: "Desencantar Item Mágico", Level: 4, Category: "Criação", KeySkill: "Arcanismo (sem teste)", ComponentCost: "25 PO", MarketPrice: "175 PO", SourceBook: "Livro do Jogador 1", Description: "Destrói um item mágico tocado, transformando-o em resíduo equivalente a um quinto do seu preço."},
		{Name: "Detectar Objeto", Level: 10, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "400 PO", MarketPrice: "1.000 PO", SourceBook: "Livro do Jogador 1", Description: "Detecta a direção e distância do exemplar mais próximo de um objeto nomeado, dentro do alcance definido pelo teste de Arcanismo."},
		{Name: "Detectar Portas Secretas", Level: 3, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "25 PO", MarketPrice: "125 PO", SourceBook: "Livro do Jogador 1", Description: "Revela portas e compartimentos secretos nas proximidades do ritualista."},
		{Name: "Discernir Mentiras", Level: 6, Category: "Adivinhação", KeySkill: "Religião", ComponentCost: "140 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Concede bônus nos testes de Intuição para discernir inverdades ditas na presença do ritualista pela duração do ritual."},
		{Name: "Disco Flutuante de Tenser", Level: 1, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Cria uma superfície circular de energia flutuante, capaz de transportar objetos colocados sobre ela."},
		{Name: "Encantar Item Mágico", Level: 4, Category: "Criação", KeySkill: "Arcanismo (sem teste)", ComponentCost: "Especial (preço do item mágico)", MarketPrice: "175 PO", SourceBook: "Livro do Jogador 1", Description: "Transforma um item normal tocado em um item mágico de nível igual ou inferior ao do ritualista."},
		{Name: "Enviar Mensagem", Level: 6, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "50 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Transmite uma mensagem mental de até 25 palavras para uma pessoa conhecida, que pode responder da mesma forma."},
		{Name: "Falar com os Mortos", Level: 6, Category: "Exploração", KeySkill: "Religião", ComponentCost: "140 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Indaga e recebe respostas do cadáver de uma criatura inteligente, que sabe tudo o que sabia em vida."},
		{Name: "Invocação Instantânea de Drawmij", Level: 12, Category: "Viagem", KeySkill: "Arcanismo (sem teste)", ComponentCost: "500 PO", MarketPrice: "2.600 PO", SourceBook: "Livro do Jogador 1", Description: "Sintoniza uma arma, implemento ou escudo ao personagem, permitindo convocá-lo à mão a qualquer momento."},
		{Name: "Item Ilusório", Level: 5, Category: "Enganação", KeySkill: "Arcanismo", ComponentCost: "25 PO", MarketPrice: "250 PO", SourceBook: "Livro do Jogador 1", Description: "Cria a ilusão de um único objeto inanimado que parece real para todos os efeitos práticos."},
		{Name: "Mão do Destino", Level: 4, Category: "Adivinhação", KeySkill: "Religião (sem teste)", ComponentCost: "70 PO", MarketPrice: "175 PO", SourceBook: "Livro do Jogador 1", Description: "Uma mão azul translúcida aparece e indica qual, dentre até três cursos de ação descritos, é a melhor opção."},
		{Name: "Mensageiro Animal", Level: 1, Category: "Exploração", KeySkill: "Natureza", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Envia um animal Miúdo não-hostil para entregar uma mensagem sussurrada a um destinatário conhecido."},
		{Name: "Montaria Fantasma", Level: 6, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "70 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 1", Description: "Conjura até oito criaturas equinas de tamanho Grande que podem ser cavalgadas pelos participantes do ritual."},
		{Name: "Observar Criatura", Level: 24, Category: "Sondagem", KeySkill: "Arcanismo", ComponentCost: "21.000 PO, mais um foco no valor de 10.000 PO", MarketPrice: "105.000 PO", SourceBook: "Livro do Jogador 1", Description: "Cria um sensor mágico adjacente a uma criatura específica, permitindo vê-la e ouvi-la à distância."},
		{Name: "Olho do Alarme", Level: 2, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "25 PO", MarketPrice: "100 PO", SourceBook: "Livro do Jogador 1", Description: "Cria olhos vigilantes intangíveis e quase invisíveis, posicionados a até 10 quadrados do local de execução."},
		{Name: "Olho do Alerta", Level: 14, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "800 PO", MarketPrice: "4.200 PO", SourceBook: "Livro do Jogador 1", Description: "Funciona como Olho do Alarme, mas também detecta e destrói automaticamente sensores de sondagem intrusos."},
		{Name: "Página Secreta", Level: 1, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Protege uma página de até 250 palavras para que não possa ser lida por outrem, bloqueando sua presença da mente do leitor."},
		{Name: "Portal Planar", Level: 18, Category: "Viagem", KeySkill: "Arcanismo", ComponentCost: "5.000 PO", MarketPrice: "17.000 PO", SourceBook: "Livro do Jogador 1", Description: "Funciona como Portal Vinculado, mas permite viajar para outros planos através de um círculo de teleporte permanente."},
		{Name: "Portal Verdadeiro", Level: 28, Category: "Viagem", KeySkill: "(consulte o texto)", ComponentCost: "50.000 PO", MarketPrice: "425.000 PO", SourceBook: "Livro do Jogador 1", Description: "Funciona como Portal Vinculado, mas sem limitação a lugares já vistos ou com círculos de teleporte permanentes."},
		{Name: "Portal Vinculado", Level: 8, Category: "Viagem", KeySkill: "Arcanismo", ComponentCost: "135 PO (consulte o texto)", MarketPrice: "680 PO", SourceBook: "Livro do Jogador 1", Description: "Cria um atalho unindo a localização do ritualista a um círculo de teleporte permanente em outro lugar do mesmo plano."},
		{Name: "Preparar Poção", Level: 1, Category: "Criação", KeySkill: "Arcanismo ou Religião (sem teste)", ComponentCost: "Especial (preço da poção/elixir)", MarketPrice: "75 PO", SourceBook: "Livro do Jogador 1", Description: "Cria uma poção ou elixir de nível igual ou inferior ao do ritualista."},
		{Name: "Proibição", Level: 20, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "5.000 PO, mais 5 pulsos de cura", MarketPrice: "25.000 PO", SourceBook: "Livro do Jogador 1", Description: "Impede que sensores de sondagem penetrem na área protegida e que criaturas se teleportem até lá."},
		{Name: "Remover Aflição", Level: 8, Category: "Restauração", KeySkill: "Cura", ComponentCost: "250 PO", MarketPrice: "680 PO", SourceBook: "Livro do Jogador 1", Description: "Neutraliza um único efeito persistente no alvo, incluindo maldições, domínio, medo, confusão ou petrificação."},
		{Name: "Repouso Tranquilo", Level: 1, Category: "Restauração", KeySkill: "Cura (sem teste)", ComponentCost: "10 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 1", Description: "Quintuplica o tempo que um cadáver adjacente pode permanecer morto e ainda ser afetado por Reviver os Mortos, e impede que se erga como morto-vivo por 150 dias."},
		{Name: "Respirar na Água", Level: 8, Category: "Exploração", KeySkill: "Arcanismo ou Natureza", ComponentCost: "135 PO", MarketPrice: "680 PO", SourceBook: "Livro do Jogador 1", Description: "Permite que até oito participantes respirem e falem normalmente debaixo d'água."},
		{Name: "Reviver os Mortos", Level: 8, Category: "Restauração", KeySkill: "Cura (sem teste)", ComponentCost: "500 PO", MarketPrice: "680 PO", SourceBook: "Livro do Jogador 1", Description: "Devolve à vida uma criatura morta há menos de 30 dias, desde que parte do cadáver esteja disponível."},
		{Name: "Silêncio", Level: 1, Category: "Proteção", KeySkill: "Arcanismo (sem teste)", ComponentCost: "30 PO", MarketPrice: "75 PO", SourceBook: "Livro do Jogador 1", Description: "Protege um único aposento contra ouvidos indiscretos, impondo penalidade nos testes de Percepção de quem tenta escutar de fora."},
		{Name: "Suportar Elementos", Level: 2, Category: "Exploração", KeySkill: "Arcanismo ou Natureza (sem teste)", ComponentCost: "20 PO", MarketPrice: "100 PO", SourceBook: "Livro do Jogador 1", Description: "Permite que até cinco participantes suportem calor extremo ou frio intenso sem serem incomodados por 24 horas."},
		{Name: "Tranca Arcana", Level: 4, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "25 PO", MarketPrice: "150 PO", SourceBook: "Livro do Jogador 1", Description: "Tranca magicamente uma porta, janela, portão ou outra forma de acesso, permitindo passagem só a quem tiver permissão."},
		{Name: "Visão Arcana", Level: 8, Category: "Sondagem", KeySkill: "Arcanismo", ComponentCost: "270 PO, mais um foco no valor de 200 PO", MarketPrice: "680 PO", SourceBook: "Livro do Jogador 1", Description: "Gera um sensor mágico num local escolhido a até 20 quadrados, permitindo ver e ouvir como se estivesse lá."},
		{Name: "Visualizar Localização", Level: 14, Category: "Sondagem", KeySkill: "Arcanismo", ComponentCost: "1.600 PO, mais um foco no valor de 1.000 PO", MarketPrice: "4.200 PO", SourceBook: "Livro do Jogador 1", Description: "Permite observar um local fixo onde o ritualista já esteve, através de um sensor mágico."},
		{Name: "Visualizar Objeto", Level: 18, Category: "Sondagem", KeySkill: "Arcanismo", ComponentCost: "7.000 PO, mais um foco no valor de 5.000 PO", MarketPrice: "17.000 PO", SourceBook: "Livro do Jogador 1", Description: "Permite observar um objeto específico de tamanho Grande ou menor, mesmo sem tê-lo visto antes, desde que descrito com clareza."},
		{Name: "Voz do Destino", Level: 26, Category: "Adivinhação", KeySkill: "Religião", ComponentCost: "45.000 PO, mais 5 pulsos de cura", MarketPrice: "225.000 PO", SourceBook: "Livro do Jogador 1", Description: "Consulta uma entidade do destino para obter orientações sobre ações futuras, ouvidas apenas pelos participantes do ritual."},

		// ── Livro do Jogador 2, Capítulo 3 — "Novos Rituais" (23 rituais) ──
		{Name: "Canto do Viajante", Level: 1, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "10 PO, mais um foco no valor de 5 PO", MarketPrice: "75 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Por 8 horas, o personagem e até oito aliados que ouviram a performance completa podem viajar mais rápido que o normal."},
		{Name: "Criar Acampamento", Level: 1, Category: "Exploração", KeySkill: "Natureza", ComponentCost: "15 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 2", Description: "Invoca centenas de pequenos espíritos da natureza para montar um acampamento completo num raio de 5 quadrados, também ocultando-o."},
		{Name: "Quintilha Eloquente", Level: 1, Category: "Enganação", KeySkill: "Arcanismo (sem teste)", ComponentCost: "10 PO, mais um foco no valor de 5 PO", MarketPrice: "50 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Pela duração, sempre que realizar um teste de Blefe o personagem pode rolar duas vezes e escolher o resultado."},
		{Name: "Florescer", Level: 2, Category: "Exploração", KeySkill: "Natureza (sem teste)", ComponentCost: "20 PO", MarketPrice: "100 PO", SourceBook: "Livro do Jogador 2", Description: "Faz com que todo terreno ao ar livre a até 20 quadrados fique repleto de folhagem (terreno acidentado) e safras produzam frutos."},
		{Name: "Forma de Árvore", Level: 2, Category: "Exploração", KeySkill: "Natureza (sem teste)", ComponentCost: "20 PO", MarketPrice: "100 PO", SourceBook: "Livro do Jogador 2", Description: "Transforma o personagem numa árvore ou arbusto Grande por até 6 horas, mantendo suas estatísticas mas sem poder usar poderes."},
		{Name: "Pirotecnia", Level: 2, Category: "Criação", KeySkill: "Arcanismo (sem teste)", ComponentCost: "20 PO", MarketPrice: "50 PO", SourceBook: "Livro do Jogador 2", Description: "Lança fogos de artifício coloridos ao céu por 1 minuto, visíveis a até 16 km de distância à noite."},
		{Name: "Afetar Fogo Mundano", Level: 3, Category: "Exploração", KeySkill: "Arcanismo ou Natureza (sem teste)", ComponentCost: "25 PO", MarketPrice: "125 PO", SourceBook: "Livro do Jogador 2", Description: "O personagem adquire controle sobre fogo mundano, podendo manipular ou extinguir chamas não-mágicas a até 10 quadrados."},
		{Name: "Canção de Ninar", Level: 3, Category: "Exploração", KeySkill: "Arcanismo", ComponentCost: "25 PO, mais um foco no valor de 20 PO", MarketPrice: "125 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "A performance do bardo deixa a audiência sonolenta, impondo penalidade em Intuição e Percepção, e pode reduzir o tempo de descanso prolongado dos aliados."},
		{Name: "Enroscar", Level: 4, Category: "Proteção", KeySkill: "Natureza", ComponentCost: "25 PO", MarketPrice: "150 PO", SourceBook: "Livro do Jogador 2", Description: "Cria uma armadilha mágica quase invisível numa área de 2 por 2 quadrados que imobiliza qualquer inimigo que entrar nela."},
		{Name: "Amizade Animal", Level: 5, Category: "Contenção", KeySkill: "Natureza", ComponentCost: "50 PO", MarketPrice: "250 PO", SourceBook: "Livro do Jogador 2", Description: "Um animal natural Miúdo se torna amigo do ritualista e realiza tarefas simples (atuar, buscar, procurar, vigiar) por um tempo determinado pelo teste de Natureza."},
		{Name: "Falar com a Natureza", Level: 5, Category: "Adivinhação", KeySkill: "Natureza", ComponentCost: "80 PO", MarketPrice: "250 PO", SourceBook: "Livro do Jogador 2", Description: "Por 10 minutos, o personagem consegue se comunicar com animais naturais e plantas mundanas."},
		{Name: "Chamado do Guia da Natureza", Level: 6, Category: "Exploração", KeySkill: "Natureza", ComponentCost: "144 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 2", Description: "Convoca um espírito da natureza que assume forma animal e guia o personagem até um destino específico pela rota mais curta."},
		{Name: "Pau-Ferro", Level: 6, Category: "Criação", KeySkill: "Natureza", ComponentCost: "75 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 2", Description: "Altera um volume de madeira para que adquira a força e a consistência do aço, ganhando resistência a dano."},
		{Name: "Travessia de Árvores", Level: 6, Category: "Viagem", KeySkill: "Arcanismo", ComponentCost: "200 PO, mais um foco no valor de 1.000 PO", MarketPrice: "1.000 PO", SourceBook: "Livro do Jogador 2", Description: "Abre um portal mágico entre duas árvores, permitindo que o ritualista e até oito aliados se desloquem instantaneamente entre elas."},
		{Name: "Vigília da Wyvern", Level: 6, Category: "Proteção", KeySkill: "Arcanismo", ComponentCost: "100 PO", MarketPrice: "360 PO", SourceBook: "Livro do Jogador 2", Description: "Cria a forma fantasmagórica de uma wyvern que protege uma área de 4 por 4 quadrados, atacando intrusos não autorizados."},
		{Name: "Canção do Sustento", Level: 8, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Nutre até dez criaturas Pequenas ou Médias como se tivessem participado de um grande banquete, concedendo +5 em testes de Tolerância pela duração. Custo de componentes e preço de mercado não confirmados com segurança na extração (layout em duas colunas ambíguo no PDF-fonte) — confirmar contra o livro físico antes de exibir esses dois valores ao jogador."},
		{Name: "Melodia da Alegria", Level: 9, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "160 PO, mais um foco no valor de 840 PO", MarketPrice: "900 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Por 10 minutos, o personagem e aliados que ouviram a performance podem rolar duas vezes em testes de Diplomacia e escolher o resultado."},
		{Name: "Ária da Revelação", Level: 10, Category: "Adivinhação", KeySkill: "Arcanismo", ComponentCost: "400 PO, mais um foco no valor de 1.000 PO", MarketPrice: "1.000 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Cada aliado que ouviu o bardo pode realizar um teste de conhecimento, recebendo um bônus baseado no resultado do teste de Arcanismo do ritualista."},
		{Name: "Balbuciar dos Tolos", Level: 10, Category: "Enganação", KeySkill: "Arcanismo (sem teste)", ComponentCost: "50 PO, mais um foco no valor de 360 PO", MarketPrice: "360 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Permite que o personagem e até cinco aliados se comuniquem numa linguagem secreta incompreensível para outras criaturas."},
		{Name: "Canção do Descanso Pleno", Level: 10, Category: "Exploração", KeySkill: "Arcanismo (sem teste)", ComponentCost: "400 PO, mais um foco no valor de 1.000 PO", MarketPrice: "1.200 PO", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Nutre até dez criaturas como se tivessem participado de um grande banquete, revitalizando-as com a vontade renovada para continuar a missão."},
		{Name: "Refrão da Verdade", Level: 10, Category: "Exploração", KeySkill: "Arcanismo", Prerequisite: "Bardo", SourceBook: "Livro do Jogador 2", Description: "Impõe uma penalidade nos testes de Blefe de criaturas a até 5 quadrados do ritualista, determinada pelo resultado do teste de Arcanismo. Custo de componentes e preço de mercado não confirmados com segurança na extração (mesma ambiguidade de coluna de Canção do Sustento) — confirmar contra o livro físico antes de exibir esses dois valores ao jogador."},
		{Name: "Reverter Portal", Level: 12, Category: "Viagem", KeySkill: "Arcanismo", ComponentCost: "500 PO", MarketPrice: "2.600 PO", SourceBook: "Livro do Jogador 2", Description: "Cria um atalho ligando a posição do personagem a um círculo de teleporte permanente em outro lugar do mesmo plano, permitindo entrada apenas pela extremidade distante."},
		{Name: "Controlar o Clima", Level: 14, Category: "Exploração", KeySkill: "Natureza", ComponentCost: "1.800 PO", MarketPrice: "4.500 PO", SourceBook: "Livro do Jogador 2", Description: "O ritualista controla as tendências gerais do clima (vento, chuva, neve, granizo) numa área de 4,5 km de raio, conforme a estação do ano."},
	}

	for _, r := range rituais {
		var existing domain.Ritual
		err := db.Where("name = ? AND edition = ?", r.Name, "4e").First(&existing).Error
		if err != nil {
			db.Create(&domain.Ritual{
				Name: r.Name, Edition: "4e", Level: r.Level, Category: r.Category,
				KeySkill: r.KeySkill, ComponentCost: r.ComponentCost, MarketPrice: r.MarketPrice,
				Prerequisite: r.Prerequisite, SourceBook: r.SourceBook, Description: r.Description,
			})
		} else {
			db.Model(&existing).Updates(map[string]interface{}{
				"level": r.Level, "category": r.Category, "key_skill": r.KeySkill,
				"component_cost": r.ComponentCost, "market_price": r.MarketPrice,
				"prerequisite": r.Prerequisite, "source_book": r.SourceBook, "description": r.Description,
			})
		}
	}
	log.Printf("  Rituais 4e: %d semeados (LJ1: 49, LJ2: 23)", len(rituais))
}
