package seed

import (
	"log"

	"rpg-manager/internal/domain"

	"gorm.io/gorm"
)

// Poderes extraídos de "Poder Primitivo" (Primal Power), livro de suplemento 4e
// que cobre as classes Bárbaro, Druida, Guardião e Xamã. O livro NÃO cobre o
// Rastreador (Seeker) — confirmado pela capa e sumário do livro.

func seedXamaSkillsPoderPrimitivo(db *gorm.DB) {
	var cls domain.Class
	if err := db.Where("name = ? AND edition = ?", "Xamã", "4e").First(&cls).Error; err != nil {
		log.Println("  ✗ Xamã 4e não encontrado")
		return
	}
	id := cls.ID

	skills := []domain.Skill{
		// ── NOVAS ESTRUTURAS — CARACTERÍSTICAS DE CLASSE (escolha) ──
		{
			Name: "Espírito de Rapina", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual arranha um adversário que esteja se movendo e um aliado utiliza a distração para disparar naquele inimigo.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação de Oportunidade", Range: "Espírito corpo a corpo 1",
			Target: "O inimigo que ativou o gatilho",
			Special: "Gatilho: um inimigo abandona um quadrado adjacente ao companheiro espiritual do xamã sem ajustar.",
			Effect: "Um aliado a até 10 quadrados do companheiro espiritual do xamã pode realizar um ataque básico à distância contra o alvo usando uma ação livre com vantagem de combate.",
			PowerType: domain.PowerUnlimited, Level: 1, IsClassFeature: true, RequiresChoice: true, ChoiceGroup: "estrutura_xama",
		},
		{
			Name: "Comando do Orador do Mundo", Edition: "4e", ClassID: &id,
			Description: "As vozes e rugidos dos espíritos primitivos despencam sobre seu adversário, paralisando-o onde está.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação de Oportunidade", Range: "Espírito corpo a corpo 1",
			Target: "O inimigo que ativou o gatilho", Attack: "Sabedoria vs. Vontade",
			Special: "Gatilho: um inimigo abandona um quadrado adjacente ao companheiro espiritual do xamã sem ajustar.",
			Hit: "O alvo para de se mover e deve usar uma ação diferente para continuar a se mover.",
			PowerType: domain.PowerUnlimited, Level: 1, IsClassFeature: true, RequiresChoice: true, ChoiceGroup: "estrutura_xama",
		},
		// ── EVOCAÇÕES SEM LIMITE DE NÍVEL 1 ──────────────────────────
		{
			Name: "Espírito da Tempestade", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual lhe concede força, canalizando uma tempestade de poder primitivo para atacar seu adversário e auxiliar um aliado.",
			Keywords: "Implemento, Primitivo, Trovejante", ActionType: "Ação Padrão", Range: "Corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "1d8 + modificador de Sabedoria de dano trovejante.",
			LevelScaling: "Nível 21: 2d8 + modificador de Sabedoria de dano trovejante.",
			Effect: "Um aliado a até 2 quadrados de você ou do seu companheiro espiritual pode realizar um teste de resistência.",
			PowerType: domain.PowerUnlimited, Level: 1,
		},
		{
			Name: "Garras da Águia", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual mergulha em seu adversário, fazendo-o negligenciar suas defesas por um breve período.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura",
			Effect: "Um aliado adjacente ao companheiro espiritual do xamã ou a até 3 quadrados do personagem pode realizar um ataque básico contra o alvo. Se o ataque daquele aliado for bem sucedido, o alvo fornece vantagem de combate até o final do próximo turno do personagem.",
			PowerType: domain.PowerUnlimited, Level: 1,
		},
		{
			Name: "Voz da Batalha", Edition: "4e", ClassID: &id,
			Description: "Você emite um grito de batalha através do seu companheiro espiritual que esmaga seu inimigo e estimula um aliado a se movimentar.",
			Keywords: "Espírito, Implemento, Primitivo, Psíquico", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "1d6 + modificador de Sabedoria de dano psíquico.",
			LevelScaling: "Nível 21: 2d6 + modificador de Sabedoria de dano psíquico.",
			Effect: "Um aliado a até 2 quadrados do seu companheiro espiritual ajusta 2 quadrados usando uma ação livre.",
			PowerType: domain.PowerUnlimited, Level: 1,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 1 ────────────────────────
		{
			Name: "Ameaça Certa", Edition: "4e", ClassID: &id,
			Description: "Com um rosnado e com um bote selvagem, seu companheiro espiritual atrai e prende a atenção de um adversário.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d6 + modificador de Sabedoria de dano e o alvo fica marcado pelo companheiro espiritual do xamã até o final do próximo turno do personagem ou até que o companheiro espiritual desapareça.",
			Special: "Espírito Protetor: a penalidade nas jogadas de ataque que o alvo sofre por estar marcado por este poder é igual a 1 + o modificador de Constituição do personagem em vez de -2.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Espíritos da Névoa da Montanha", Edition: "4e", ClassID: &id,
			Description: "Uma névoa congelante surge a partir do seu companheiro espiritual, coalescendo em volta dos seus inimigos e permitindo que seus aliados os ataquem mais facilmente.",
			Keywords: "Congelante, Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "2d10 + modificador de Sabedoria de dano congelante. Até o final do próximo turno do xamã, qualquer aliado que realizar um ataque de área ou contíguo que inclua o companheiro espiritual do xamã na área de efeito recebe +1 de bônus de poder nas jogadas de ataque daquele ataque.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Fúria do Falcão Tempestuoso", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual mergulha em seu inimigo e descarrega um relâmpago que tarda momentaneamente.",
			Keywords: "Elétrico, Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Effect: "Antes do ataque, o xamã pode mover seu companheiro espiritual 3 quadrados. Espírito Vigilante: o número de quadrados que o xamã pode mover o companheiro espiritual é igual a 2 + seu modificador de Destreza.",
			Hit: "1d8 + modificador de Sabedoria de dano elétrico. Até o final do próximo turno do xamã, quando um aliado atinge um inimigo adjacente ao companheiro espiritual do xamã, aquele inimigo sofre dano elétrico adicional igual ao modificador de Destreza do xamã.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Garras do Rompedor de Correntes", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual crava suas garras em seu adversário, tirando o equilíbrio do inimigo e deixando-o à mercê do ataque de um aliado.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "1d10 + modificador de Sabedoria de dano. Um aliado do personagem adjacente ao alvo pode realizar um ataque básico corpo a corpo contra o alvo usando uma ação livre.",
			Special: "Espírito Perseguidor: o aliado recebe um bônus na jogada de ataque igual ao modificador de Inteligência do personagem.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		{
			Name: "Sarça Aliada", Edition: "4e", ClassID: &id,
			Description: "Você arremessa espinheiros do mundo espiritual em seu inimigo, e então faz com que eles brotem do seu companheiro espiritual, limitando o movimento dos inimigos próximos.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d6 + modificador de Sabedoria de dano. Até o final do próximo turno do personagem, os inimigos de iniciarem os turnos deles adjacentes a seu companheiro espiritual ficam lentos durante aquele turno.",
			Special: "Espírito do Orador do Mundo: um inimigo que iniciar o turno dele adjacente ao companheiro espiritual do personagem fica imobilizado em vez de lento durante aquele turno.",
			PowerType: domain.PowerEncounter, Level: 1,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 1 ──────────────────────────────
		{
			Name: "Cascata Espiritual", Edition: "4e", ClassID: &id,
			Description: "Você convoca o espírito das nascentes montanhosas para repetidamente despencarem contra os inimigos que se aproximarem do seu companheiro espiritual.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d10 + modificador de Sabedoria de dano.",
			Effect: "Na primeira vez em que um aliado atinge um inimigo adjacente ao companheiro espiritual do xamã, o ataque causa 1d6 de dano adicional naquele inimigo. Na segunda vez, o ataque causa 2d6 de dano adicional. Na terceira vez, o ataque causa 3d6 de dano adicional. Este efeito se encerra após o terceiro ataque atingir o inimigo ou até o final do encontro.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Espírito da Raiz Rochosa", Edition: "4e", ClassID: &id,
			Description: "A terra se ergue ao seu comando, dispersando seus inimigos e criando um bastião para você e seus aliados.",
			Keywords: "Implemento, Primitivo, Zona", ActionType: "Ação Padrão", Range: "Explosão de área 1 a até 5 quadrados",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "O xamã conduz o alvo 2 quadrados para um quadrado fora da explosão e o alvo fica derrubado.",
			Miss: "O xamã conduz o alvo 1 quadrado.",
			Effect: "A explosão cria uma zona de terra protetora que dura até o final do encontro. A zona é considerada terreno acidentado para os inimigos. O xamã e aliados adquirem cobertura enquanto permanecerem dentro da zona.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Espírito da Sombra do Pesar", Edition: "4e", ClassID: &id,
			Description: "Você liberta um espírito da morte e da penúria em seu adversário, deixando-o fraco e apático.",
			Keywords: "Implemento, Primitivo, Psíquico", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "O alvo fica pasmo, lento e sofre 5 de dano psíquico contínuo (TR encerra todos).",
			Miss: "O alvo fica pasmo até o final do próximo turno do personagem e fica lento (TR encerra).",
			Effect: "Até o final do encontro, o alvo sofre -5 de penalidade nos testes de resistência enquanto estiverem adjacentes ao companheiro espiritual do personagem.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Rajada de Espinhos", Edition: "4e", ClassID: &id,
			Description: "Você dispara uma barragem de espinhos envenenados em seus adversários.",
			Keywords: "Implemento, Primitivo, Venenoso", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Cada criatura dentro da rajada", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d8 + modificador de Sabedoria de dano e 5 de dano venenoso contínuo (TR encerra). Enquanto durar este dano, seus aliados recebem +2 de bônus de poder nas jogadas de ataque contra o alvo.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		{
			Name: "Espírito do Grande Vigilante", Edition: "4e", ClassID: &id,
			Description: "O espírito do Grande Vigilante mostra o caminho para a vitória, apontando fraquezas nas defesas de seu inimigo enquanto ampara as fraquezas de seus companheiros.",
			Keywords: "Primitivo", ActionType: "Ação Padrão", Range: "Explosão de área 1 a até 10 quadrados",
			Target: "Um ou dois aliados dentro da explosão",
			Effect: "Cada alvo pode realizar um ataque básico usando uma ação livre. Até o final do encontro, os aliados adjacentes ao companheiro espiritual não fornecem vantagem de combate.",
			PowerType: domain.PowerDaily, Level: 1,
		},
		// ── EVOCAÇÕES UTILITÁRIAS DE NÍVEL 2 ──────────────────────────
		{
			Name: "Espírito do Grande Felino", Edition: "4e", ClassID: &id,
			Description: "O espírito de um felino magnificente obscurece você, concedendo sua graça a você e a seus aliados.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Até o final do encontro, os aliados a até 3 quadrados do xamã podem se levantar usando uma ação mínima e quando um aliado a até 3 quadrados do xamã ajustar, aquele aliado pode ajustar 1 quadrado adicional.",
			PowerType: domain.PowerDaily, Level: 2,
		},
		{
			Name: "Espírito do Zéfiro", Edition: "4e", ClassID: &id,
			Description: "Uma suave brisa sopra ao redor do seu companheiro espiritual e aprimora os ataques à distância dos seus aliados.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Até o final do encontro, o xamã e aliados recebem +1 de bônus de poder nas jogadas de ataque à distância contra os inimigos adjacentes ao companheiro espiritual do xamã. Além disso, usando uma ação livre, o xamã pode encerrar o efeito deste poder para fornecer a um aliado a até 10 quadrados do xamã +2 de bônus nas jogadas de ataque à distância até o final do próximo turno do seu personagem.",
			PowerType: domain.PowerDaily, Level: 2,
		},
		{
			Name: "Perseguição Engajadora", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual segue de perto seus inimigos, prevenindo que eles escapem da sua ira.",
			Keywords: "Espírito, Primitivo", ActionType: "Reação Imediata", Range: "Pessoal",
			Special: "Gatilho: um inimigo que iniciou o turno dele adjacente ao companheiro espiritual do xamã encerra o movimento dele não mais adjacente ao companheiro espiritual.",
			Effect: "O xamã move seu companheiro espiritual para um quadrado adjacente ao inimigo que ativou o gatilho.",
			PowerType: domain.PowerEncounter, Level: 2,
		},
		{
			Name: "Raízes Protetoras", Edition: "4e", ClassID: &id,
			Description: "Raízes finas crescem a partir do seu companheiro espiritual para cobrir você e seus aliados em uma camada protetora.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Mínima", Range: "Espírito explosão contígua 1",
			Target: "O xamã e cada aliado dentro da explosão",
			Effect: "Cada alvo adquire resistência contra todos os tipos de dano igual ao modificador de Constituição do xamã até o final do encontro.",
			PowerType: domain.PowerDaily, Level: 2,
		},
		{
			Name: "Vigilância do Falcão Tempestuoso", Edition: "4e", ClassID: &id,
			Description: "Conforme seus adversários saltam para atacar, o espírito do Falcão Tempestuoso concede velocidade para seus aliados enquanto eles se preparam para o assalto.",
			Keywords: "Primitivo", ActionType: "Nenhuma Ação", Range: "Explosão contígua 5",
			Target: "O xamã e cada aliado dentro da explosão",
			Special: "Gatilho: o xamã joga a iniciativa no começo de um encontro.",
			Effect: "O xamã conduz cada alvo 3 quadrados. Cada alvo pode sacar uma arma ou um implemento usando uma ação livre.",
			PowerType: domain.PowerDaily, Level: 2,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 3 ─────────────────────────
		{
			Name: "Caça Espiritual", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual inicia a caçada, se focando inteiramente em sua presa.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Special: "Espírito Perseguidor: o xamã recebe +2 de bônus de poder nas jogadas de ataque caso não haja criaturas a até 3 quadrados do alvo.",
			Hit: "2d10 + modificador de Sabedoria de dano, ou 3d10 + modificador de Sabedoria de dano caso não haja criaturas adjacentes ao alvo.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Espírito da Raposa Astuta", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual transforma-se em uma esperta raposa e distrai seus inimigos, permitindo seus aliados atacar.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Um aliado",
			Effect: "O alvo pode realizar um ataque básico corpo a corpo usando uma ação livre. Caso este ataque seja bem sucedido, um segundo aliado adjacente ao companheiro espiritual do xamã pode realizar um ataque básico usando uma ação livre.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Espírito da Sede por Sangue", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual baba ao farejar sangue, seu frenesi feral se espalha pelos seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude. Caso o alvo esteja sangrando, o xamã recebe +2 de bônus na jogada de ataque.",
			Hit: "2d8 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, os aliados adjacentes ao companheiro espiritual do xamã recebem +2 de bônus de poder nas jogadas de ataque e nas jogadas de dano contra criaturas sangrando.",
			Special: "Espírito Vigilante: o bônus nas jogadas de ataque e de dano é igual ao modificador de Destreza do xamã.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Guardião da Montanha Inabalável", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual torna-se uma criatura de rocha e terra, providenciando uma barreira protetora a você e a seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "1d10 + modificador de Sabedoria de dano e o alvo é empurrado 2 quadrados.",
			Effect: "Até o final do próximo turno do xamã, o xamã e seus aliados recebem +1 de bônus de poder em todas as defesas enquanto estiverem adjacentes ao companheiro espiritual do xamã.",
			Special: "Espírito do Orador do Mundo: o bônus de poder em todas as defesas é igual ao modificador de Constituição do xamã.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		{
			Name: "Mandíbulas Capturadoras", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual apanha seu inimigo em seu focinho, prendendo-o firme para os ataques dos seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "1d8 + modificador de Sabedoria de dano e o alvo fica imobilizado até o final do próximo turno do personagem.",
			Special: "Espírito Protetor: até o final do próximo turno do personagem, seus aliados podem flanquear os inimigos com o companheiro espiritual do xamã e os aliados flanqueando um inimigo com o companheiro espiritual do xamã recebem um bônus nas jogadas de ataque contra aquele inimigo igual ao modificador de Constituição do personagem.",
			PowerType: domain.PowerEncounter, Level: 3,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 5 ──────────────────────────────
		{
			Name: "Espirais da Serpente Mundo", Edition: "4e", ClassID: &id,
			Description: "A terra treme, e um rugido distante ressoa pelo campo de batalha enquanto a Serpente Mundo se manifesta.",
			Keywords: "Implemento, Primitivo, Zona", ActionType: "Ação Padrão", Range: "Explosão de área 1 a até 10 quadrados",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Fortitude",
			Hit: "2d6 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Effect: "A explosão cria uma zona de espirais espectrais que dura até o final do encontro. Quando um inimigo atingir um aliado que esteja dentro da zona, aquele inimigo sofre dano igual ao modificador de Sabedoria do xamã.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Espírito do Desfecho da Batalha", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual rasga o inimigo, prometendo uma sina rápida.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d10 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Effect: "Quando um aliado fracassa e o alvo com um ataque corpo a corpo, o alvo sofre 5 de dano e realiza um teste de resistência. Caso o teste de resistência seja bem sucedido, este efeito se encerra. Caso contrário, ele dura até o final do encontro.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Espírito do Sangue Vingativo", Edition: "4e", ClassID: &id,
			Description: "Você preenche seus aliados com o poder dos espíritos do sangue — entidades primitivas que anseiam por violência, sangue e vingança.",
			Keywords: "Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Um ou dois aliados",
			Effect: "Cada alvo pode realizar uma investida usando uma ação livre e causa 1d10 de dano adicional caso o ataque da investida seja bem sucedido. Além disso, até o final do encontro, cada alvo recebe +2 de bônus nas jogadas de ataque e jogadas de dano quando realizam ataques de investida.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Vento da Dor e do Socorro", Edition: "4e", ClassID: &id,
			Description: "Um espírito do vento rodeia o seu companheiro espiritual, permitindo-o desferir um golpe congelante contra seu adversário ou um abraço restaurador em um aliado.",
			Keywords: "Congelante, Cura, Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "3d8 + modificador de Sabedoria de dano congelante.",
			Miss: "Metade do dano.",
			Effect: "O primeiro aliado a recuperar pontos de vida enquanto estiver adjacente ao companheiro espiritual do xamã recupera 1d8 pontos de vida adicionais. O segundo aliado que o fizer recupera 2d8 pontos de vida adicionais e o terceiro aliado que o fizer recupera 3d8 pontos de vida adicionais. Este efeito se encerra após o terceiro aliado recuperar esses pontos de vida adicionais ou até o final do encontro.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		{
			Name: "Ventos do Deserto Escaldante", Edition: "4e", ClassID: &id,
			Description: "Ventos ardentes queimam e espalham seus inimigos, enquanto você ou o seu companheiro espiritual percorrem estas correntes cruzando o campo de batalha.",
			Keywords: "Flamejante, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Rajada contígua 3",
			Target: "Cada criatura dentro da rajada", Attack: "Sabedoria vs. Fortitude",
			Hit: "2d6 + modificador de Sabedoria de dano flamejante e o alvo é conduzido um número de quadrados igual ao modificador de Sabedoria do xamã.",
			Miss: "Metade do dano e o xamã conduz o alvo 1 quadrado.",
			Effect: "Antes ou após o ataque, o xamã conduz a si mesmo ou seu companheiro espiritual um número de quadrados igual ao deslocamento do xamã.",
			PowerType: domain.PowerDaily, Level: 5,
		},
		// ── EVOCAÇÕES UTILITÁRIAS DE NÍVEL 6 ──────────────────────────
		{
			Name: "Abrigo do Companheiro Espiritual", Edition: "4e", ClassID: &id,
			Description: "Você cria um escudo de energia primitiva para proteger seu companheiro espiritual.",
			Keywords: "Espírito, Primitivo", ActionType: "Interrupção Imediata", Range: "Pessoal",
			Special: "Gatilho: um inimigo atinge o companheiro espiritual do xamã.",
			Effect: "O companheiro espiritual do xamã recebe +4 de bônus na defesa visada pelo ataque.",
			PowerType: domain.PowerEncounter, Level: 6,
		},
		{
			Name: "Espírito da Vingança", Edition: "4e", ClassID: &id,
			Description: "Conforme seu adversário oprime você, você libera sua reserva de energia espiritual para revigorar seus aliados.",
			Keywords: "Cura, Primitivo", ActionType: "Interrupção Imediata", Range: "Explosão contígua 10",
			Target: "Cada aliado dentro da explosão",
			Special: "Gatilho: um inimigo reduz o xamã a 0 pontos de vida ou menos.",
			Effect: "Cada alvo pode gastar um pulso de cura. Além disso, até o final do próximo turno do personagem, cada alvo recebe +2 de bônus nas jogadas de ataque contra o inimigo que ativou o gatilho.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		{
			Name: "Espírito de Cura", Edition: "4e", ClassID: &id,
			Description: "Um confortante espírito da lareira surge diante de você, confortando você e seus aliados.",
			Keywords: "Cura, Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 3",
			Target: "Cada aliado dentro da explosão",
			Effect: "Cada alvo pode gastar um pulso de cura e recupera 1d6 pontos de vida. Até o final do próximo turno do xamã, o xamã e seus aliados podem retomar o fôlego usando uma ação mínima enquanto estiverem adjacentes ao companheiro espiritual do xamã.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		{
			Name: "Estimular da Matilha", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual incita seus aliados, motivando-os a avançar para matar.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Mínima", Range: "Espírito explosão contígua 1",
			Target: "O xamã e cada aliado dentro da explosão",
			Effect: "O xamã conduz cada alvo um número de quadrados igual ao modificador de Sabedoria do xamã.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		{
			Name: "Força da Chama Eterna", Edition: "4e", ClassID: &id,
			Description: "Você concede ao seu aliado o auxílio de um espírito do fogo, que queima mais intensamente conforme aquele aliado derrota seus inimigos.",
			Keywords: "Cura, Flamejante, Primitivo", ActionType: "Ação Mínima", Range: "Pessoal 5",
			Target: "Um aliado",
			Effect: "Até o final do encontro, sempre que o alvo reduzir um inimigo a 0 pontos de vida, ele recupera 5 pontos de vida e cada inimigo adjacente àquele aliado sofre 2 de dano flamejante.",
			PowerType: domain.PowerDaily, Level: 6,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 7 ─────────────────────────
		{
			Name: "Espírito Lampejante", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual dardeja pelo campo de batalha, buscando oportunidades para auxiliar seus aliados a desferirem ataques mortais.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 1",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "1d10 + modificador de Sabedoria de dano.",
			Effect: "Enquanto qualquer aliado estiver adjacente ao companheiro espiritual do xamã, o aliado recebe +2 de bônus nas jogadas de dano para cada inimigo que o xamã atingir com este ataque. Este efeito dura até o final do próximo turno do personagem.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Esmagar das Ondas Aprisionadoras", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual transforma-se em uma onda opressora — um maremoto para seus adversários e uma corrente guia para seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 2",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "1d8 + modificador de Sabedoria de dano e o alvo fica lento até o final do próximo turno do personagem.",
			Effect: "Cada aliado dentro da explosão recebe +3 de bônus no deslocamento até o final do próximo turno do personagem.",
			Special: "Espírito do Orador do Mundo: até o final do próximo turno do personagem, cada aliado dentro da explosão recebe um bônus em todas as defesas contra ataques de oportunidade igual a 2 + o modificador de Constituição do personagem.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Espírito da Fraqueza", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual esculpe uma runa carmesim na carne de seu inimigo, enfraquecendo aquele adversário e deixando-o vulnerável ao golpe de um aliado.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "O alvo fica enfraquecido até o final do próximo turno do personagem. Um aliado adjacente ao alvo pode realizar um ataque básico corpo a corpo contra o alvo usando uma ação livre com vantagem de combate.",
			Special: "Espírito Perseguidor: o aliado recebe um bônus nas jogadas de dano igual ao modificador de Inteligência do xamã.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Névoa Vermelha-Sangue", Edition: "4e", ClassID: &id,
			Description: "Conforme seu companheiro espiritual açoita seu adversário, tentáculos de neblina crescem a partir dos ferimentos, circulando os inimigos próximos e dificultando seus ataques.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d8 + modificador de Sabedoria de dano. Até o final do próximo turno do personagem, os inimigos sofrem -2 de penalidade em todas as defesas enquanto estiverem adjacentes ao companheiro espiritual do xamã.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		{
			Name: "Revoada de Águias Guardiãs", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual altera-se na forma de uma revoada de águias caçadoras que mergulham do céu, usando suas garras para criar brechas para seus aliados e para afastar seus inimigos para longe.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 2",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Fortitude",
			Hit: "1d10 + modificador de Sabedoria de dano. O xamã conduz o alvo 3 quadrados.",
			Effect: "Caso o xamã atinja ao menos um alvo, o xamã conduz cada aliado dentro da explosão 3 quadrados.",
			Special: "Espírito Vigilante: o xamã conduz o alvo 3 quadrados adicionais.",
			PowerType: domain.PowerEncounter, Level: 7,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 9 ──────────────────────────────
		{
			Name: "Controlar o Espírito", Edition: "4e", ClassID: &id,
			Description: "Você abre uma fenda de energia espiritual deslumbrante que detona seus inimigos, fortalece seu companheiro espiritual e aprimora sua habilidade de convocar espíritos.",
			Keywords: "Implemento, Primitivo, Psíquico, Zona", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Cada criatura dentro da rajada", Attack: "Sabedoria vs. Reflexos",
			Hit: "1d10 + modificador de Sabedoria de dano. O companheiro espiritual do xamã recebe +2 de bônus de poder nas jogadas de ataque contra o alvo até o final do encontro.",
			Miss: "Metade do dano.",
			Effect: "A rajada cria uma zona de energia deslumbrante que dura até o final do encontro. Enquanto o companheiro espiritual do xamã permanecer dentro da zona, os poderes de espírito do xamã recebem um bônus nas jogadas de dano igual ao modificador de Sabedoria do xamã.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Espírito da Ascenção Térrea", Edition: "4e", ClassID: &id,
			Description: "Um espírito de terra e rocha irrompe do solo abaixo do seu adversário. A presença do espírito recobra a força de seus aliados, que são revigorados pelo espírito a cada ataque.",
			Keywords: "Conjuração, Cura, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura",
			Effect: "O xamã conjura um espírito da terra em um quadrado desocupado adjacente ao alvo. O espírito dura até o final do próximo turno do xamã. O espírito ocupa 1 quadrado. Cada quadrado a até 2 quadrados do espírito é considerado terreno acidentado para os inimigos. Quando um aliado no interior dessa área atinge um inimigo, aquele aliado recupera 5 pontos de vida (uma vez por rodada). Usando uma ação de movimento, o xamã pode mover o espírito 5 quadrados. Quando o espírito aparece, ele realiza o seguinte ataque contra o alvo.",
			Attack: "Sabedoria vs. Fortitude",
			Hit: "3d6 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Special: "Sustentação Mínima: o espírito persiste.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Invocar o Espírito Discordante", Edition: "4e", ClassID: &id,
			Description: "Você obriga um desagradável espírito a vincular-se ao seu inimigo, criando tanta discordância dentro do inimigo que os companheiros dele perdem a concentração.",
			Keywords: "Confiável, Implemento, Primitivo, Psíquico", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "2d10 + modificador de Sabedoria de dano psíquico. Até o final do encontro, cada inimigo que não seja o alvo sofre -2 de penalidade nas jogadas de ataque e nos testes de resistência enquanto permanecerem a até 5 quadrados do alvo.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		{
			Name: "Sacrifício Explosivo", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual se sacrifica em uma explosão de energia, atingindo as criaturas próximas.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 2",
			Target: "Cada criatura dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d6 + modificador de Sabedoria de dano e o alvo fica pasmo (TR encerra).",
			Miss: "Metade do dano.",
			Effect: "O companheiro espiritual do xamã desaparece e o xamã não pode convocá-lo de volta até após o final do seu próximo turno.",
			PowerType: domain.PowerDaily, Level: 9,
		},
		// ── EVOCAÇÕES UTILITÁRIAS DE NÍVEL 10 ─────────────────────────
		{
			Name: "Brisa Estimulante", Edition: "4e", ClassID: &id,
			Description: "Você invoca uma suave vento que envolve seu companheiro espiritual e se estende em direção de seus aliados, ajudando-os a superar os efeitos nocivos.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Na primeira vez que um aliado fracassar em um teste de resistência enquanto estiver adjacente ao companheiro espiritual do xamã, o aliado pode refazer o teste de resistência. Na segunda vez, o aliado pode refazer o teste com +1 de bônus. Na terceira vez, o aliado pode refazer o teste com +2 de bônus. Este efeito se encerra após o terceiro teste de resistência refeito ou no final do encontro.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Escudo da Floresta Imortal", Edition: "4e", ClassID: &id,
			Description: "Você desperta os espíritos adormecidos da floresta para proteger seus aliados do perigo.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Até o final do encontro, o xamã e seus aliados recebem +2 de bônus de poder em todas as defesas enquanto permanecerem a até 5 quadrados do companheiro espiritual do xamã. Além disso, quando um inimigo atingir um aliado a até 10 quadrados do xamã, o xamã pode usar uma interrupção imediata para encerrar este efeito e fornecer àquele aliado +6 de bônus em todas as defesas contra o ataque.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Resiliência da Raiz Rochosa", Edition: "4e", ClassID: &id,
			Description: "Você concede a um aliado a resiliência das montanhas para absorver os golpes que poderiam aleijar outra criatura.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "À distância 5",
			Target: "Um aliado",
			Effect: "Até o final do encontro, o alvo recebe pontos de vida temporários igual ao modificador de Sabedoria do xamã no início de cada um dos turnos dele.",
			PowerType: domain.PowerDaily, Level: 10,
		},
		{
			Name: "Véu do Crepúsculo", Edition: "4e", ClassID: &id,
			Description: "Você penetra o mundo espiritual, tecendo fios de noite primitiva para cobrir a si e a seus aliados em um véu de invisibilidade.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 1",
			Target: "O xamã e cada aliado dentro da explosão",
			Effect: "Cada alvo fica invisível até atacar ou até o final do próximo turno do xamã.",
			PowerType: domain.PowerEncounter, Level: 10,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 13 ────────────────────────
		{
			Name: "Atraindo a Atenção", Edition: "4e", ClassID: &id,
			Description: "O ataque cruel do seu companheiro espiritual obriga seu inimigo a atentá-lo.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "4d6 + modificador de Sabedoria de dano e o alvo fica marcado pelo companheiro espiritual do xamã até o final do próximo turno do personagem ou até o companheiro espiritual desaparecer.",
			Special: "Espírito Protetor: a penalidade nas jogadas de ataque que o alvo sofre por estar marcado por este poder é igual ao modificador de Constituição do xamã em vez de -2.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Espírito do Disparo Mortal", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual rapidamente se mescla com seu aliado, concedendo-o o olhar de um caçador resoluto.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Um aliado",
			Effect: "O alvo realiza um ataque básico usando uma ação livre. Caso o ataque seja bem sucedido, ele causa dano máximo.",
			Special: "Espírito Perseguidor: o alvo recebe um bônus nas jogadas de ataque e jogadas de dano igual ao modificador de Inteligência do xamã.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Espírito do Vale Esquecido", Edition: "4e", ClassID: &id,
			Description: "Conforme seu espírito companheiro ataca, espíritos que se parecem com fogos-fátuo de fumaça cinza azulada são vomitados por ele.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "3d8 + modificador de Sabedoria de dano. Até o final do próximo turno do personagem, um aliado que realizar um ataque de área ou contíguo que inclua o companheiro espiritual na área de efeito recebe vantagem de combate contra cada alvo daquele ataque.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Espírito Voraz", Edition: "4e", ClassID: &id,
			Description: "Alimento para os espíritos é amparo para seus aliados.",
			Keywords: "Cura, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "3d10 + modificador de Sabedoria de dano. Caso este ataque reduza o alvo a 0 pontos de vida, um aliado adjacente ao companheiro espiritual do xamã recupera pontos de vida igual a metade do nível do xamã + o modificador de Sabedoria do xamã.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		{
			Name: "Espírito da Guerra", Edition: "4e", ClassID: &id,
			Description: "Você convoca uma ventania criada a partir dos gritos de guerra de centenas de compôs de batalha antigos para castigar e distrair seus adversários.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d10 + modificador de Sabedoria de dano. Cada inimigo adjacente ao companheiro espiritual do xamã fornece vantagem de combate até o final do próximo turno do xamã.",
			Special: "Espírito do Orador do Mundo: até o final do próximo turno do personagem, seus aliados recebem um bônus nas jogadas de dano contra os inimigos adjacentes ao companheiro espiritual do xamã igual ao modificador de Constituição do xamã.",
			PowerType: domain.PowerEncounter, Level: 13,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 15 ─────────────────────────────
		{
			Name: "Caçada do Pai Árvore", Edition: "4e", ClassID: &id,
			Description: "Árvores irrompem do chão, colidindo com seus inimigos e permitindo que seus aliados se esgueirem ao redor dos troncos para alcançarem posições superiores.",
			Keywords: "Implemento, Primitivo, Zona", ActionType: "Ação Padrão", Range: "Explosão de área 1 a até 10 quadrados",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "4d6 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Effect: "A explosão cria uma zona de árvores que dura até o final do encontro. A zona é considerada terreno acidentado para seus inimigos. O xamã e seus aliados adquirem cobertura enquanto permanecerem dentro da zona. Quando um aliado iniciar o turno dele dentro da zona, o xamã pode usar uma ação livre para conduzir aquele aliado 2 quadrados.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Espírito do Oceano", Edition: "4e", ClassID: &id,
			Description: "Você invoca o poderoso espírito do Oceano Primitivo, na qual se choca com seu inimigo antes de fluir para seu companheiro espiritual para conceder força a seus aliados.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "3d10 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Effect: "Na primeira vez que um aliado atingir um inimigo adjacente ao companheiro espiritual do xamã, o ataque causa 1d10 de dano adicional naquele inimigo. Na segunda vez, o ataque causa 2d10 de dano adicional. Na terceira vez, o ataque causa 3d10 de dano adicional. Este efeito se encerra após o terceiro ataque atingir um inimigo adjacente ao companheiro espiritual do xamã ou no final do encontro.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Espírito Reparador", Edition: "4e", ClassID: &id,
			Description: "Trabalhando com seus aliados, seu companheiro espiritual investe em um ataque feroz contra seu inimigo e então concede vigor a um aliado próximo.",
			Keywords: "Implemento, Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "3d8 + modificador de Sabedoria de dano ou 5d8 + modificador de Sabedoria de dano se ao menos um aliado estiver adjacente ao companheiro espiritual do xamã.",
			Miss: "Metade do dano.",
			Effect: "No final de cada turno do personagem até o final do encontro, um aliado adjacente ao companheiro espiritual do xamã recebe 5 + o modificador de Sabedoria do xamã pontos de vida temporários.",
			PowerType: domain.PowerDaily, Level: 15,
		},
		{
			Name: "Pino Espiritual", Edition: "4e", ClassID: &id,
			Description: "Você comanda seu companheiro espiritual a prender seu adversário no lugar.",
			Keywords: "Implemento, Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "2d10 + modificador de Sabedoria de dano e o alvo fica imobilizado (TR encerra).",
			Special: "Primeira Falha no Teste de Resistência: o alvo fica impedido em vez de imobilizado (TR encerra).",
			Miss: "Metade do dano e o alvo fica imobilizado (TR encerra).",
			PowerType: domain.PowerDaily, Level: 15,
		},
		// ── EVOCAÇÕES UTILITÁRIAS DE NÍVEL 16 ─────────────────────────
		{
			Name: "Regeneração do Espírito", Edition: "4e", ClassID: &id,
			Description: "Um brilho de luz restauradora envolve seus aliados e se intensifica enquanto eles estiverem próximos ao seu companheiro espiritual.",
			Keywords: "Cura, Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 5",
			Target: "Uma ou duas criaturas dentro da explosão",
			Effect: "Até o final do encontro, cada alvo adquire regeneração 5 enquanto estiver sangrando. A regeneração aumenta para 10 enquanto o alvo estiver adjacente ao companheiro espiritual do xamã.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Rosnado Condutor", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual finta para colocar seu adversário em uma melhor posição para o ataque do seu aliado.",
			Keywords: "Espírito, Primitivo", ActionType: "Interrupção Imediata", Range: "Espírito corpo a corpo 1",
			Target: "O aliado que ativou o gatilho",
			Special: "Gatilho: um aliado adjacente ao companheiro espiritual do xamã fracassa um ataque em um inimigo.",
			Effect: "O alvo pode refazer o ataque e recebe um bônus de poder na jogada de ataque igual ao modificador de Inteligência do xamã.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Uivo Curandeiro", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual emite um uivo de coragem que fortalece os aliados próximos.",
			Keywords: "Cura, Espírito, Primitivo", ActionType: "Ação Mínima", Range: "Espírito explosão contígua 3",
			Target: "O xamã e cada aliado dentro da explosão",
			Effect: "Cada alvo recupera pontos de vida como se ele tivesse gasto um pulso de cura. Caso a explosão inclua ao menos três inimigos, cada alvo recupera pontos de vida adicionais igual ao modificador de Sabedoria do xamã.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Carcaça de Galhos", Edition: "4e", ClassID: &id,
			Description: "Uma massa enredada de galhos, vinhas e folhas fornece proteção contra os ataques de seus inimigos e suaviza os ferimentos de seus aliados.",
			Keywords: "Conjuração, Primitivo", ActionType: "Ação Mínima", Range: "Muralha de área 4 a até 20 quadrados",
			Effect: "O xamã conjura uma muralha de galhos e vinhas. A muralha pode ter até 2 quadrados de altura e deve estar sob uma superfície sólida, ela dura até o final do próximo turno do personagem. A muralha fornece cobertura superior, porém as criaturas adjacentes a ela podem realizar ataques à distância através da muralha sem o -5 de penalidade nas jogadas de ataque. Entrar em um quadrado na muralha exige 2 quadrados adicionais de movimento. Um aliado adjacente à muralha no início do turno do aliado recebe 5 + o modificador de Constituição pontos de vida temporários.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		{
			Name: "Presença do Espírito Ancestral", Edition: "4e", ClassID: &id,
			Description: "Você convoca o espírito de um dos seus combatentes ancestrais a se fundir com um aliado, concedendo-o seu conhecimento de batalha e proteção espiritual para o aliado.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 5",
			Target: "Um aliado dentro da explosão",
			Effect: "Até o final do encontro, o alvo recebe um bônus nas jogadas de dano igual ao modificador de Inteligência do xamã. Enquanto o alvo estiver adjacente ao companheiro espiritual do xamã, o bônus de poder aumenta em 2. Além disso, quando um inimigo atingir o alvo, o xamã pode usar uma interrupção imediata para encerrar este efeito e fazer com que o ataque cause metade do dano.",
			PowerType: domain.PowerDaily, Level: 16,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 17 ────────────────────────
		{
			Name: "Arremesso do Javali", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual arremessa no ar seu inimigo, deixando-o vulnerável ao ataque à distância dos seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "1d10 + modificador de Sabedoria de dano e o xamã conduz o alvo 2 quadrados. O xamã então move seu companheiro espiritual para um quadrado adjacente ao alvo e cada aliado do xamã a até 10 quadrados do alvo pode realizar um ataque básico à distância contra o alvo usando uma ação livre.",
			Special: "Espírito Vigilante: os aliados recebem um bônus de poder nas jogadas de dano dos ataques básicos à distância igual ao modificador de Destreza do xamã.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Caçar e Regressar", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual investe à frente por um momento, atacando um inimigo antes de regressar em direção aos seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Special: "Espírito Perseguidor: o xamã recebe +2 de bônus na jogada de ataque caso não haja criaturas a até 3 quadrados do alvo.",
			Hit: "3d8 + modificador de Sabedoria de dano ou 4d8 + modificador de Sabedoria de dano caso não haja criaturas adjacentes ao alvo.",
			Effect: "Após o ataque, o xamã pode mover seu companheiro espiritual 4 quadrados.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Espinheiro Aliado", Edition: "4e", ClassID: &id,
			Description: "Galhos espinhosos dos arvoredos do reino espiritual irrompem do seu companheiro espiritual para perfurar e enredar seu inimigo.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d8 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, os inimigos que iniciarem os turnos deles adjacentes ao companheiro espiritual do xamã ficam impedidos até o final do próximo turno do xamã.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Garras do Estripador de Carne", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual rasga seu adversário, deixando-o desequilibrado e vulnerável ao ataque do seu aliado.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d10 + modificador de Sabedoria de dano e um aliado adjacente ao alvo pode realizar um ataque básico corpo a corpo contra o alvo usando uma ação livre. Caso o ataque seja bem sucedido, o alvo fica derrubado.",
			Special: "Espírito Protetor: caso o alvo se levante no próximo turno dele, um aliado do xamã adjacente ao alvo pode realizar um ataque básico corpo a corpo contra o alvo usando uma ação livre.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		{
			Name: "Lança Espiritual", Edition: "4e", ClassID: &id,
			Description: "O corpo do seu companheiro espiritual ondula momentaneamente conforme uma lança de energia brilhante salta dele em direção a seu inimigo.",
			Keywords: "Energético, Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito à distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "3d10 + modificador de Sabedoria de dano energético.",
			PowerType: domain.PowerEncounter, Level: 17,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 19 ─────────────────────────────
		{
			Name: "Espírito da Alma do Caçador", Edition: "4e", ClassID: &id,
			Description: "O espírito de um grande caçador aparece e ataca seu adversário com um poderoso ataque. Ele então se vincula com um aliado para continuar o massacre.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "5d8 + modificador de Sabedoria de dano.",
			Miss: "Metade do dano.",
			Effect: "Escolha um aliado dentro do alcance. Aquele aliado recebe +5 de bônus de poder nas jogadas de dano contra o alvo até o final do encontro. Enquanto aquele aliado estiver adjacente ao companheiro espiritual do xamã, adicione o modificador de Inteligência do xamã ao bônus de poder.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Proteção do Pai Árvore", Edition: "4e", ClassID: &id,
			Description: "Você invoca o Pai Árvore para punir seus inimigos por atacarem e para recompensar seus aliados por lutarem bravamente.",
			Keywords: "Cura, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Um ou dois inimigos dentro da rajada", Attack: "Sabedoria vs. Fortitude",
			Hit: "3d8 + modificador de Sabedoria de dano e o alvo sofre -4 de penalidade nas jogadas de ataque (TR encerra).",
			Miss: "Metade do dano.",
			Effect: "Cada aliado sangrando dentro da rajada recupera pontos de vida como se o aliado tivesse gasto um pulso de cura.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Tambor dos Ancestrais", Edition: "4e", ClassID: &id,
			Description: "Um tambor espectral criado pelos seus ancestrais se manifesta em suas mãos, ressoando até que você o ponha de lado ou até seu poder atingir um crescendo.",
			Keywords: "Cura, Implemento, Primitivo, Trovejante", ActionType: "Ação Padrão", Range: "Explosão contígua 1",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Vontade",
			Hit: "2d8 + modificador de Sabedoria de dano trovejante.",
			Effect: "Um aliado dentro da explosão pode gastar um pulso de cura.",
			Special: "Sustentação Padrão: o tamanho da explosão aumenta em 1 e o xamã realiza o ataque novamente. Após o xamã usar este poder como uma explosão contígua 3, ele não poderá ser sustentado.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		{
			Name: "Vento da Morte e da Misericórdia", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual une-se ao espírito do vento para enlaçar seu inimigo em correntes frias. Seus aliados são revigorados por esta união.",
			Keywords: "Congelante, Cura, Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "5d10 + modificador de Sabedoria de dano congelante.",
			Miss: "Metade do dano.",
			Effect: "O primeiro aliado que recuperar pontos de vida enquanto estiver adjacente ao companheiro espiritual do xamã recupera 1d12 pontos de vida adicionais. O segundo aliado que recuperar pontos de vida enquanto estiver adjacente ao companheiro espiritual recupera 2d12 pontos de vida adicionais, e o terceiro aliado que recuperar pontos de vida enquanto estiver adjacente ao companheiro espiritual recupera 3d12 pontos de vida adicionais. Este efeito se encerra após o terceiro aliado recuperar esses pontos de vida adicionais ou no final do encontro.",
			PowerType: domain.PowerDaily, Level: 19,
		},
		// ── EVOCAÇÕES UTILITÁRIAS DE NÍVEL 22 ─────────────────────────
		{
			Name: "Espírito do General Astuto", Edition: "4e", ClassID: &id,
			Description: "O espírito de um antigo líder lendário se estabelece em seu corpo, inspirando seus aliados e feitos poderosos.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Pessoal",
			Effect: "Até o final do encontro, quando um aliado a até 3 quadrados do companheiro espiritual do xamã gasta um ponto de ação para realizar um ataque e fracassa todos os alvos com ele, aquele aliado recupera o ponto de ação e pode gastá-lo novamente neste encontro.",
			PowerType: domain.PowerDaily, Level: 22,
		},
		{
			Name: "Espíritos de Recuperação", Edition: "4e", ClassID: &id,
			Description: "Espíritos luminosos de antigos curandeiros tribais aparecem em volta de seus aliados, tratando de seus ferimentos.",
			Keywords: "Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 2",
			Target: "Cada aliado dentro da explosão",
			Effect: "Cada alvo pode realizar um teste de resistência contra um efeito que possa ser encerrado com um sucesso em um teste de resistência. O alvo que obtiver sucesso recebe 1d10 + o modificador de Sabedoria do xamã pontos de vida temporários.",
			PowerType: domain.PowerEncounter, Level: 22,
		},
		{
			Name: "Medicina das Diversas Formas", Edition: "4e", ClassID: &id,
			Description: "Você espalha ervas medicinais entre seus aliados, curando o corpo, a mente e o espírito.",
			Keywords: "Cura, Primitivo", ActionType: "Ação Mínima", Range: "Rajada contígua 5",
			Target: "Cada aliado dentro da rajada",
			Effect: "Cada alvo pode escolher entre realizar um teste de resistência, gastar um pulso de cura ou adquirir 20 pontos de vida temporários.",
			PowerType: domain.PowerEncounter, Level: 22,
		},
		{
			Name: "Reino Espiritual", Edition: "4e", ClassID: &id,
			Description: "Você dissolve sua conexão com seu companheiro espiritual por um breve período para que ela possa infundir-se com os espíritos locais, expandindo sua influência pelo mundo.",
			Keywords: "Espírito, Primitivo, Zona", ActionType: "Ação Mínima", Range: "Explosão de área 3 a até 10 quadrados",
			Special: "Especial: o companheiro espiritual do xamã deve estar dentro da explosão. Sustentação Mínima: a zona persiste.",
			Effect: "O companheiro espiritual do xamã desaparece (caso o xamã possua mais de um companheiro espiritual, todos desaparecem). A explosão cria uma zona de espíritos que dura até o final do próximo turno do xamã. Todos os efeitos que se referem a estar adjacente a ou até certo número de quadrados do companheiro espiritual do xamã em vez disso se aplicam aos alvos no interior da zona. O xamã não pode usar convocar companheiro espiritual enquanto a zona persistir.",
			PowerType: domain.PowerDaily, Level: 22,
		},
		{
			Name: "Renascimento Natural", Edition: "4e", ClassID: &id,
			Description: "Ao sentir que um aliado está prestes a cruzar o véu da morte, você invoca os espíritos da terra para impedirem que a alma parta. Os espíritos restauram a saúde do aliado, o imbuindo com poder primitivo.",
			Keywords: "Cura, Primitivo", ActionType: "Ação Mínima", Range: "Explosão contígua 20",
			Target: "Um aliado morrendo dentro da explosão",
			Effect: "O alvo recupera pontos de vida como se ele tivesse gasto um pulso de cura. Até o final do encontro, o alvo fica imune aos efeitos que imobilizam, impedem ou que deixam lento.",
			PowerType: domain.PowerEncounter, Level: 22,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 23 ────────────────────────
		{
			Name: "Espírito da Montanha Vingativa", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual manifesta a essência nas montanhas intransponíveis, formando uma barreira impenetrável contra seus adversários.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 3",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d8 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, o alvo fica impedido e não pode teleportar.",
			Special: "Espírito do Orador do Mundo: até o final do próximo turno do xamã, seus aliados recebem um bônus nas jogadas de ataque contra o alvo igual ao modificador de Constituição do xamã.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Espírito do Carneiro", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual transforma-se em um aglomerado de carneiros saltadores espirituais, que aprimoram as investidas de seus aliados nos adversários.",
			Keywords: "Espírito, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 2",
			Target: "Cada aliado dentro da explosão",
			Effect: "Cada alvo pode realizar uma investida em um inimigo usando uma ação livre com +4 de bônus de poder na jogada de ataque e +5 na jogada de dano. Caso o ataque da investida seja bem sucedido, o alvo empurra o inimigo 3 quadrados.",
			Special: "Espírito Protetor: o número de quadrados que o alvo empurra o inimigo é igual a 2 + o modificador de Constituição do xamã.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Laços Vermelho-Sangue", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual fere seu adversário e então persegue impiedosamente seus inimigos.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "3d8 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, os inimigos sofrem -4 de penalidade em todas as defesas enquanto estiverem adjacentes ao companheiro espiritual do xamã. Além disso, caso um inimigo inicie o turno dele adjacente ao companheiro espiritual do xamã mas não encerre o turno dele adjacente ao espírito, o xamã pode, usando uma ação no final daquele turno, mover o companheiro espiritual um número de quadrados igual ao valor de deslocamento do xamã para o quadrado mais próximo daquele inimigo.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Ninho da Águia", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual ascende aos céus, mergulhando em seus inimigos e conduzindo-os na direção de seus aliados.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito explosão contígua 3",
			Target: "Cada inimigo dentro da explosão", Attack: "Sabedoria vs. Fortitude",
			Hit: "2d6 + modificador de Sabedoria de dano e o xamã conduz o alvo 2 quadrados. O alvo fornece vantagem de combate para os aliados do xamã até o final do próximo turno do xamã.",
			Special: "Espírito Vigilante: até o final do próximo turno do xamã, o alvo não recebe os benefícios de cobertura contra os aliados do xamã.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		{
			Name: "Salto Poderoso do Espírito", Edition: "4e", ClassID: &id,
			Description: "Seu companheiro espiritual salta entre os inimigos e desfere um ataque furioso que inspira seus aliados a atacarem tão ferozmente quanto.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito corpo a corpo 1",
			Target: "Uma, duas ou três criaturas", Attack: "Sabedoria vs. Reflexos",
			Hit: "2d10 + modificador de Sabedoria de dano.",
			Effect: "Após cada jogada de ataque, o xamã pode mover seu companheiro espiritual um número de quadrados igual ao seu valor de deslocamento. Jogue um d6 para cada alvo que o xamã atingir e some todos os resultados. Até o final do próximo turno do xamã, seus aliados recebem um bônus nas jogadas de dano igual ao resultado enquanto permanecerem adjacentes ao companheiro espiritual do xamã.",
			Special: "Espírito Perseguidor: some o modificador de Inteligência do xamã ao bônus das jogadas de dano.",
			PowerType: domain.PowerEncounter, Level: 23,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 25 ─────────────────────────────
		{
			Name: "Abrigo do Pacifista", Edition: "4e", ClassID: &id,
			Description: "Um círculo de rochas espirituais se formam diante de você e uma neblina tranquilizadora envolve aqueles dentro do círculo.",
			Keywords: "Implemento, Primitivo, Psíquico, Zona", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Cada inimigo dentro da rajada", Attack: "Sabedoria vs. Vontade",
			Hit: "4d10 + modificador de Sabedoria de dano psíquico e o alvo fica pasmo até o final do próximo turno do xamã.",
			Effect: "A rajada cria uma zona de tranquilidade até o final do próximo turno do personagem. As criaturas dentro da zona sofrem uma penalidade nas jogadas de ataque igual ao modificador de Constituição do xamã. Os aliados do xamã não sofrem essa penalidade enquanto permanecerem adjacentes ao companheiro espiritual do xamã.",
			Special: "Sustentação Mínima: a zona persiste.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Clarim do Mestre da Caçada", Edition: "4e", ClassID: &id,
			Description: "O imenso espírito de um mestre da caçada selvagem aparece acima de você e sopra um clarim, abalando a coragem de seus adversários e convocando seus aliados para a batalha.",
			Keywords: "Medo, Implemento, Primitivo, Psíquico", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Cada inimigo dentro da rajada", Attack: "Sabedoria vs. Vontade",
			Hit: "5d6 + modificador de Sabedoria de dano psíquico e o alvo fica imobilizado (TR encerra).",
			Miss: "Metade do dano e o alvo fica lento (TR encerra).",
			Effect: "Cada aliado dentro da rajada recebe um bônus nas jogadas de dano igual ao modificador de Inteligência do xamã e as criaturas que estiverem lentas ou imobilizadas fornecem vantagem de combate para os aliados. Esses efeitos duram até o final do encontro.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Espírito Divisor", Edition: "4e", ClassID: &id,
			Description: "Você separa a alma de seu adversário do corpo e estabelece conexão com ela, forçando seu inimigo a reestabelecer o vínculo com ela ou perecer. Seu companheiro espiritual então utiliza a força vital do adversário para curar os aliados.",
			Keywords: "Cura, Necrótico, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "3d10 + modificador de Sabedoria de dano necrótico e o alvo fica desmaiado inconsciente (TR encerra).",
			Special: "Cada Falha no Teste de Resistência: cada aliado adjacente ao companheiro espiritual do xamã recupera 5 pontos de vida. Terceira Falha no Teste de Resistência: o alvo cai a 0 pontos de vida.",
			Miss: "Metade do dano e o alvo fica pasmo (TR encerra).",
			Effect: "Até o final do encontro, os aliados sangrando que iniciarem os turnos deles adjacentes ao companheiro espiritual do xamã recuperam 5 pontos de vida.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		{
			Name: "Gambito do Falcão Tempestuoso", Edition: "4e", ClassID: &id,
			Description: "Você invoca a generosidade do Falcão Tempestuoso, tomando seus inimigos com uma rajada de poder e suspendendo você e seus aliados em direção do céu com graça primitiva.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Rajada contígua 5",
			Target: "Cada inimigo dentro da rajada", Attack: "Sabedoria vs. Reflexos",
			Hit: "5d6 + modificador de Sabedoria de dano e o alvo fica lento (TR encerra). Uma criatura voando cai.",
			Miss: "Metade do dano.",
			Effect: "Até o final do encontro, quando o xamã ou um de seus aliados iniciar o turno dele a até 5 quadrados do companheiro espiritual do xamã, aquele personagem adquire deslocamento de voo igual ao valor de deslocamento daquele personagem e pode pairar até o final do próximo turno dele.",
			PowerType: domain.PowerDaily, Level: 25,
		},
		// ── EVOCAÇÕES POR ENCONTRO DE NÍVEL 27 ────────────────────────
		{
			Name: "Aliado Nobre-Bélico", Edition: "4e", ClassID: &id,
			Description: "Um antigo líder do seu povo emerge do reino espiritual para atacar seu inimigo, compartilhando o conhecimento da fraqueza de seus adversários para seu companheiro espiritual antes de regressar para seu lugar de honra.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "3d8 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, seus aliados recebem +5 de bônus de poder nas jogadas de ataque e jogadas de dano com poderes de ataque sem limite enquanto estiverem adjacentes ao companheiro espiritual do xamã.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		{
			Name: "Caçador Aéreo", Edition: "4e", ClassID: &id,
			Description: "Você invoca o espírito do grande caçador aéreo para exterminar seu adversário. Conforme a sombra do espírito se move pelo campo de batalha, a atenção do adversário é atraída pelo perigo espreitando acima.",
			Keywords: "Espírito, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Espírito à distância 5",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "4d10 + modificador de Sabedoria de dano. Até o final do próximo turno do xamã, seus aliados recebem +2 de bônus nas jogadas de ataque à distância contra o alvo enquanto os aliados estiverem adjacentes ao companheiro espiritual do xamã.",
			Special: "Espírito Vigilante: o bônus nas jogadas de ataque à distância é igual a 1 + o modificador de Destreza do xamã.",
			PowerType: domain.PowerEncounter, Level: 27,
		},
		// ── EVOCAÇÕES DIÁRIAS DE NÍVEL 29 ─────────────────────────────
		{
			Name: "Coração do Tumulto", Edition: "4e", ClassID: &id,
			Description: "A confusão reina tudo ao seu redor enquanto você redireciona a instintual incitação por violência das criaturas para os oponentes de sua escolha.",
			Keywords: "Primitivo", ActionType: "Ação Padrão", Range: "Pessoal",
			Effect: "Como a primeira ação de cada turno do xamã até o final do encontro, o xamã pode usar uma ação livre para fazer com que uma criatura a até 2 quadrados do companheiro espiritual do xamã realize um ataque básico usando uma ação livre contra outra criatura à escolha do xamã.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Espírito do Ódio Flamejante", Edition: "4e", ClassID: &id,
			Description: "Um espírito do ódio ardente penetra seu adversário e o consome por dentro. Quando o seu inimigo cai, seus aliados se regozijam.",
			Keywords: "Cura, Flamejante, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Fortitude",
			Hit: "2d10 + modificador de Sabedoria de dano flamejante e 15 de dano flamejante contínuo (TR encerra). Caso este poder reduza o alvo a 0 pontos de vida, cada aliado adjacente ao companheiro espiritual do xamã pode gastar um pulso de cura.",
			Miss: "Metade do dano e 10 de dano flamejante contínuo (TR encerra).",
			Effect: "Até o final do encontro, quando um aliado adjacente ao companheiro espiritual do xamã atinge um inimigo, aquele inimigo sofre 5 de dano flamejante contínuo (TR encerra).",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Risada da Primavera", Edition: "4e", ClassID: &id,
			Description: "Uma brisa fresca rodopia em volta do seu inimigo, confundindo seus ataques.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Vontade",
			Hit: "O alvo sofre -2 de penalidade nos testes de resistência e o dano das jogadas de ataque do alvo é reduzido para 0 (TR encerra).",
			Miss: "O alvo fica enfraquecido (TR encerra).",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Torrente Espiritual", Edition: "4e", ClassID: &id,
			Description: "Com o som de choque das ondas, um grande espírito desfere golpes em seu inimigo, o espírito então regride para dentro do seu companheiro espiritual, aguardando para auxiliar seus aliados a abater seus adversários novamente.",
			Keywords: "Implemento, Primitivo", ActionType: "Ação Padrão", Range: "À distância 10",
			Target: "Uma criatura", Attack: "Sabedoria vs. Reflexos",
			Hit: "7d10 + modificador de Sabedoria de dano.",
			Effect: "Na primeira vez que um aliado atingir um inimigo adjacente ao companheiro espiritual do xamã, o ataque causa 1d12 de dano adicional naquele inimigo. Na segunda vez, o ataque causa 2d12 de dano adicional. Na terceira vez, o ataque causa 3d12 de dano adicional. Este efeito se encerra após o terceiro ataque atingir um inimigo ou no final do encontro.",
			PowerType: domain.PowerDaily, Level: 29,
		},
		{
			Name: "Vinhas de Sangue Espiritual", Edition: "4e", ClassID: &id,
			Description: "Vinhas vermelhas e verdes crescem do solo, enredando seus inimigos. Você pode destruir uma vinha para liberar a energia primitiva que ela carrega, curando um aliado próximo.",
			Keywords: "Conjuração, Cura, Implemento, Primitivo", ActionType: "Ação Padrão", Range: "Explosão contígua 5",
			Effect: "O xamã conjura vinhas em quatro quadrados desocupados dentro da explosão. As vinhas duram até o final do próximo turno do xamã. Quando as vinhas aparecem, cada vinha realiza o ataque a seguir. Usando uma ação padrão, o xamã pode fazer com que cada vinha realize o ataque novamente. Uma criatura pode ser atingida por este poder apenas uma vez por rodada.",
			Target: "Uma criatura adjacente à vinha", Attack: "Sabedoria vs. Reflexos",
			Hit: "3d8 + modificador de Sabedoria de dano e o alvo fica impedido (TR encerra).",
			Special: "Sustentação Mínima: as vinhas persistem. Se o xamã sustentar, um aliado naquele quadrado ou adjacente ao quadrado pode gastar um pulso de cura ou recuperar 20 pontos de vida.",
			PowerType: domain.PowerDaily, Level: 29,
		},
	}

	for _, s := range skills {
		upsertSkill(db, s, id)
	}
	log.Println("  ✓ Poderes de Xamã (Poder Primitivo) semeados")
}
